import requests
from bs4 import BeautifulSoup
from typing import TextIO
import re

myresult=['https://dodge.ptplace.com/productDetail/_pn=141049?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141050?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141051?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141052?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141055?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141057?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141063?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141065?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141066?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141071?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141072?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141073?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141076?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141077?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141079?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141081?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141083?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141085?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141087?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141094?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141098?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141100?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141103?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141105?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141106?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141108?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141110?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141120?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141122?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141124?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141131?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141132?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141134?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141136?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141138?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141139?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141143?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141144?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141145?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141146?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141147?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141148?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141150?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141155?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141156?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141157?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141159?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141160?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141161?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141162?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141163?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141170?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141173?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141175?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141177?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141178?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141181?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141182?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141185?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141187?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141188?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141189?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141198?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141199?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141201?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141202?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141203?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141204?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141209?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141220?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141221?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141222?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141225?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141227?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141228?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141230?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141232?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141233?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141241?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141251?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141252?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141254?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141255?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141257?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141258?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141263?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141264?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141267?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141271?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141273?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141274?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141278?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141285?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141286?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141294?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141295?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141297?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141298?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141304?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141307?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141311?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141317?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141319?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141320?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141322?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141323?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141324?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141325?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141327?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141330?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141332?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141337?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141339?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141340?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141343?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141344?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141345?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141346?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141348?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141349?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141350?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141351?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141352?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141353?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141356?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141357?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141358?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141361?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141363?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141364?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141365?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141368?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141369?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141370?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141372?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141373?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141375?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141376?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141377?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141378?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141379?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141380?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141381?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141385?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141386?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141387?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141388?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141389?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141390?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141391?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141393?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141395?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141397?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141400?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141402?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141403?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141404?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141405?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141406?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141407?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141408?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141409?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141410?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141411?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141412?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141414?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141416?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141418?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141420?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141422?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141425?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141427?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141429?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141431?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141433?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141435?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141437?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141440?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141441?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141442?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141443?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141444?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141445?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141446?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141447?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141448?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141449?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141450?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141451?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141454?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141455?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141456?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141457?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141462?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141463?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141466?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141467?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141468?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141469?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141473?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141475?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141478?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141479?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141484?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141485?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141486?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141490?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141492?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141493?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141496?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141506?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141507?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141509?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141510?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141511?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141514?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141515?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141516?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141520?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141522?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141523?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141524?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141526?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141527?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141529?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141530?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141531?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141532?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141533?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141536?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141538?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141539?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141540?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141542?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141543?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141545?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141546?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141548?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141549?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141551?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141552?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141559?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141561?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141563?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141568?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141570?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141571?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141575?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141578?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141579?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141581?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141583?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141586?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141587?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141588?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141590?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141591?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141592?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141593?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141595?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141598?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141601?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141602?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141603?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141604?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141605?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141608?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141609?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141610?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141611?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141613?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141614?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141617?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141618?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141619?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141620?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141624?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141628?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141631?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141634?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141635?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141637?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141639?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141640?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141641?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141643?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141645?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141660?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141662?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141664?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141665?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141669?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141672?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141677?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141678?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141680?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141682?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141684?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141687?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141691?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141692?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141693?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141694?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141695?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141699?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141700?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141701?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141704?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141720?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141721?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141722?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141724?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141727?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141728?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141729?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141731?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141733?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141744?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141745?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141750?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141751?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141752?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141753?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141754?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141755?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141756?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141758?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141764?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141765?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141766?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141767?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141768?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141770?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141772?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141773?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141775?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141784?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141785?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141787?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141788?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141789?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141790?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141798?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141799?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141837?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141838?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141893?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141896?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141992?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=141994?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=142040?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=142042?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=142069?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=142079?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230050?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230053?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230056?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230059?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230062?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230065?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230068?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230071?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230074?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230077?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230080?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230134?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230137?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=230140?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231063?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231069?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231075?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231087?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231096?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231102?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231108?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231114?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231120?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231126?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231135?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231141?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=231150?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389839?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389923?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389924?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389925?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389926?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389927?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389928?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389929?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389930?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389931?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389932?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389933?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389934?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389935?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389936?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389937?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389938?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389939?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389940?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389941?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=389996?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=394124?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=394294?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=394295?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=394420?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=394469?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395024?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395038?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395783?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395784?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395785?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395786?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395787?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=395788?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=403892?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421243?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421244?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421245?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421246?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421247?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421248?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421249?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421250?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421251?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421252?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421253?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421254?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421255?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421256?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421257?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421258?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421259?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421260?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421261?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421262?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421263?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421264?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421265?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421266?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421267?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421268?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421269?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421270?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421271?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421272?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421273?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421274?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421275?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421276?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421277?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421278?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421279?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421280?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421282?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421283?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421284?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421285?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421286?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421287?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421288?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421289?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421290?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421291?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421292?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421293?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421294?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421380?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421395?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421396?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421399?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421403?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421438?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421439?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421440?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421441?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421442?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421443?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421444?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421445?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=421446?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422001?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422003?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422005?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422007?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422009?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422011?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422013?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422015?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422017?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422019?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422021?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422023?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422025?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422027?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422029?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422030?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422031?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422035?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422036?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422054?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422064?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422123?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422124?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422134?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422137?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422140?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422148?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422154?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422155?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422161?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422164?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422174?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422206?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422207?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422323?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422325?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422327?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422328?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422331?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422353?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422356?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422362?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422371?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422389?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422450?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422479?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422511?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422525?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422529?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422531?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422535?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422538?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422542?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422543?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422544?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422545?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422555?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422556?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422560?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422567?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422571?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422572?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422573?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422576?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422580?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422582?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422594?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422595?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422596?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422597?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422599?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422600?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422601?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422602?reference=PartSearchListLink']

for row in myresult:

 try:

    product_url = row

    #page = requests.get(product_url)

    headers = {"User-Agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)", "Referer": "http://example.com"}

    result = requests.get(product_url, headers=headers)

    if result.status_code == 200:

        print("site woking")

    else:

        print("site not working"+str(result.status_code))

    #a = (result.content.decode())


    soup = BeautifulSoup(result.content,'html.parser')

    #print(soup.prettify())





    bread = soup.find("ol",class_="breadcrumb pb-0 mb-0 px-0 pt-3 pt-md-0").find_all("li")
    list1 = []
    for b in bread:
        list1.append(b.text.strip())
    print(list1)





    # qnt = (soup.prettify().replace('data-ship-pack-quantity="', "raptor:").split("raptor:")[1].split('"')[0])

    #weight = soup.find("div",class_="rta sidebar__shipping-pane")



    #detail = soup.find("div",class_="copyTextSection textSection")
    #image enhanced-content__carousel-main-image image--loaded
    #soup.find("span",attrs={'data-automated-test':'leaf'})


    c = (product_url)
    print(c)



    # zxqw = qnt
    #https://static.grainger.com/rp/s/is/image/Grainger/29DJ11_GC01?hei=804&wid=804
    try:


     prod = soup.find_all("bdo",class_="data-label text-uppercase text-transparent-dark")


     specs = soup.find_all("td",class_="w-50 bg-white css-k6e94w ewehtpn0")



     i = 0
    except:
        pass
    if(len(prod)>0):

     while i < len(prod):


        j = 0

        while j < len(specs):

            z = (prod[i].text if prod else "not given")
            print(z)

            i += 1

            x = (specs[j].text if specs else "not given")
            print(x)

            j += 1
            save_details: TextIO = open("dodge-2222.txt", "a+", encoding="utf-8")
            save_details.write("\n"+c+"\t"+" / ".join(list1)+"\t"+"RP_"+z+"\t"+"RP_"+x)
            save_details.close()
            print("\n**Record stored into txt file.**")
    else:
        save_details: TextIO = open("dodge-2222.txt", "a+", encoding="utf-8")
        save_details.write("\n" + c + "\t" + " / ".join(list1))
        save_details.close()
        print("\n**Record stored into txt file.**")





 except AttributeError:

   pass
