import requests
from bs4 import BeautifulSoup
from typing import TextIO
import re

myresult=[
'https://dodge.ptplace.com/productDetail/_pn=139078?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139084?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139087?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139088?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139089?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139090?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139091?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139092?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139093?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139094?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139095?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139096?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139097?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139098?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139099?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139100?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139101?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139103?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139104?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139105?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139106?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139107?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139108?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139109?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139110?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139112?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139113?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139115?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139116?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139118?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139119?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139120?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139122?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139124?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139125?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139126?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139127?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139128?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139132?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139133?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139136?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139137?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139139?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139141?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139144?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139148?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139149?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139151?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139153?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139156?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139157?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139159?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139160?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139161?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139162?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139163?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139166?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139167?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139168?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139170?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139171?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139172?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139179?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139180?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139183?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139184?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139185?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139189?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139191?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139201?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139204?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139205?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139206?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139209?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139210?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139211?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139212?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139213?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139215?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139218?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139219?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139224?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139225?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139227?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139228?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139229?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139230?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139231?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139232?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139233?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139235?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139236?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139237?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139238?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139239?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139240?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139241?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139244?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139245?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139247?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139248?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139250?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139251?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139252?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139253?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139254?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139255?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139256?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139257?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139258?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139259?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139261?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139263?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139264?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139265?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139266?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139269?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139270?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139271?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139273?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139274?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139275?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139276?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139277?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139278?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139279?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139280?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139283?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139286?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139287?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139288?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139290?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139292?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139296?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139297?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139298?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139300?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139302?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139304?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139306?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139308?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139309?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139310?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139311?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139312?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139313?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139314?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139319?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139321?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139323?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139325?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139326?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139327?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139328?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139329?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139330?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139333?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139334?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139338?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139341?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139342?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139344?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139345?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139346?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139347?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139348?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139349?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139351?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139352?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139354?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139355?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139356?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139357?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139361?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139364?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139365?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139366?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139367?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139369?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139370?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139371?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139374?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139375?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139376?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139377?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139378?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139383?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139385?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139386?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139388?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139389?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139390?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139391?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139393?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139394?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139395?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139405?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139406?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139414?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139416?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139418?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139419?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139421?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139422?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139424?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139425?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139427?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139429?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139431?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139433?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139434?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139435?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139436?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139437?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139438?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139439?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139440?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139441?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139442?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139443?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139444?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139446?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139447?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139452?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139453?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139455?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139456?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139457?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139458?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139460?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139468?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139493?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139494?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139497?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139498?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139499?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139502?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139503?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139504?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139505?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139507?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139509?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139510?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139511?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139512?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139520?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139522?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139525?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139527?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139529?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139530?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139536?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139538?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139541?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139542?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139543?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139544?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139546?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139547?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139548?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139553?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139554?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139556?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139558?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139559?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139562?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139563?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139564?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139565?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139566?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139568?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139569?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139571?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139573?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139574?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139575?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139576?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139578?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139579?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139581?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139582?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139583?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139584?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139586?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139591?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139593?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139595?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139597?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139598?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139600?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139601?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139602?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139604?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139607?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139611?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139614?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139617?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139618?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139619?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139620?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139621?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139622?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139623?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139625?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139626?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139627?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139628?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139630?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139632?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139633?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139634?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139636?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139637?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139638?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139641?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139642?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139645?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139646?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139647?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139648?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139649?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139656?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139657?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139658?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139659?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139660?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139661?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139662?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139663?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139664?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139665?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139667?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139668?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139669?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139670?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139673?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139674?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139675?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139676?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139677?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139679?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139683?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139684?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139686?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139687?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139689?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139693?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139695?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139696?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139699?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139700?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139701?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139702?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139703?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139704?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139705?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139707?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139709?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139710?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139712?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139713?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139714?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139715?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139718?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139719?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139720?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139721?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139722?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139723?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139724?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139725?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139726?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139734?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139735?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139736?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139737?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139739?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139741?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139743?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139744?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139745?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139747?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139748?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139749?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139750?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139751?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139754?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139756?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139759?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139763?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139767?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139768?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139770?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139771?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139773?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139774?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139776?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139777?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139779?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139780?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139782?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139783?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139785?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139786?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139788?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139790?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139792?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139795?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139796?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139798?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139800?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139801?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139805?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139806?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139807?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139810?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139811?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139814?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139819?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139820?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139821?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139823?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139825?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139826?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139828?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139829?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139830?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139831?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139832?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139835?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139836?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139839?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139840?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139843?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139844?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139845?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139847?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139848?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139849?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139850?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139851?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139852?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139853?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139854?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139855?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139856?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139859?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139860?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139861?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139862?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139864?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139866?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139867?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139868?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139869?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139870?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139871?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139873?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139875?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139876?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139877?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139879?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139880?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139881?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139882?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139884?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139885?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139886?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139887?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139888?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139891?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139892?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139893?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139895?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139896?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139897?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139898?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139901?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139902?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139903?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139904?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139905?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139906?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139907?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139909?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139910?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139915?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139918?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139920?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139921?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139922?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139923?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139924?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139926?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139929?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139932?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139936?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139937?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139939?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139940?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139942?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139943?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139944?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139947?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139948?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139950?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139951?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139953?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139954?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139959?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139961?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139962?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139963?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139964?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139965?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139966?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139967?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139968?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139971?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139972?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139973?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139974?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139975?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139976?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139977?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139979?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139980?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139981?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139982?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139983?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139984?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139985?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139986?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139989?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139990?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139992?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139993?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139994?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139995?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139996?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139997?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=139998?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140000?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140001?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140002?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140004?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140005?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140007?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140008?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140009?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140012?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140013?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140016?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140017?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140018?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140019?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140021?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140022?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140023?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140025?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140026?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=140030?reference=PartSearchListLink']

for row in myresult:

 try:

    product_url = row

    #page = requests.get(product_url)

    headers = {"User-Agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)", "Referer": "http://example.com"}

    result = requests.get(product_url, headers=headers)

    if result.status_code == 200:

        print("site woking")

    else:

        print("site not working"+str(result.status_code))

    #a = (result.content.decode())


    soup = BeautifulSoup(result.content,'html.parser')

    #print(soup.prettify())





    bread = soup.find("ol",class_="breadcrumb pb-0 mb-0 px-0 pt-3 pt-md-0").find_all("li")
    list1 = []
    for b in bread:
        list1.append(b.text.strip())
    print(list1)





    # qnt = (soup.prettify().replace('data-ship-pack-quantity="', "raptor:").split("raptor:")[1].split('"')[0])

    #weight = soup.find("div",class_="rta sidebar__shipping-pane")



    #detail = soup.find("div",class_="copyTextSection textSection")
    #image enhanced-content__carousel-main-image image--loaded
    #soup.find("span",attrs={'data-automated-test':'leaf'})


    c = (product_url)
    print(c)



    # zxqw = qnt
    #https://static.grainger.com/rp/s/is/image/Grainger/29DJ11_GC01?hei=804&wid=804
    try:


     prod = soup.find_all("bdo",class_="data-label text-uppercase text-transparent-dark")


     specs = soup.find_all("td",class_="w-50 bg-white css-k6e94w ewehtpn0")



     i = 0
    except:
        pass
    if(len(prod)>0):

     while i < len(prod):


        j = 0

        while j < len(specs):

            z = (prod[i].text if prod else "not given")
            print(z)

            i += 1

            x = (specs[j].text if specs else "not given")
            print(x)

            j += 1
            save_details: TextIO = open("dodge-4444.txt", "a+", encoding="utf-8")
            save_details.write("\n"+c+"\t"+" / ".join(list1)+"\t"+"RP_"+z+"\t"+"RP_"+x)
            save_details.close()
            print("\n**Record stored into txt file.**")
    else:
        save_details: TextIO = open("dodge-4444.txt", "a+", encoding="utf-8")
        save_details.write("\n" + c + "\t" + " / ".join(list1))
        save_details.close()
        print("\n**Record stored into txt file.**")





 except AttributeError:

   pass
