import requests
from bs4 import BeautifulSoup
from typing import TextIO
import re

myresult=['https://dodge.ptplace.com/productDetail/_pn=422603?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422606?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422720?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422731?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422783?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422786?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422789?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422843?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422851?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422921?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422927?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422931?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422964?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422978?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422979?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422980?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422981?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422982?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422983?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422984?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422985?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422986?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422987?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422988?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422989?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422990?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422991?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422992?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=422996?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423100?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423102?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423104?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423106?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423108?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423110?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423112?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423114?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423116?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423118?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423120?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423122?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423124?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423125?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423126?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423127?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423128?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423129?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423130?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423131?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423132?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423133?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423134?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423135?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423136?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423137?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423138?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423139?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423140?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423143?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423144?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423146?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423147?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423148?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423149?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423372?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423373?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423374?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=423375?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=424335?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=427897?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=427899?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=427902?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=427903?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=427905?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430153?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430155?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430198?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430535?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430539?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430559?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430625?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430694?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430695?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430743?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430763?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430807?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430831?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430911?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430912?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430940?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430941?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430942?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430943?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430964?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430965?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430973?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=430986?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431125?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431138?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431146?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431199?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431389?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431564?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431566?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431576?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431579?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431651?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431674?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431677?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431723?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431739?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=431890?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432153?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432181?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432184?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432187?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432190?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432193?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432196?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432220?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432221?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432234?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432245?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432280?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432287?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432342?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432383?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432401?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432474?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432497?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432519?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432634?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432695?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432755?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432799?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432808?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432937?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432979?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=432989?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433057?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433248?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433258?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433261?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433290?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433299?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433300?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433301?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433326?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433339?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433363?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433364?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433365?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433374?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433376?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433378?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433379?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433391?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433395?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433396?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433399?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433400?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433401?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433403?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433416?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433427?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433433?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433434?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433453?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433455?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433458?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433466?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433467?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433468?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433476?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433481?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433484?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433485?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433493?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433504?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433506?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433514?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433516?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433544?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433556?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433560?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433595?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433597?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433603?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433604?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433666?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=433686?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434075?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434098?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434100?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434101?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434163?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434164?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434170?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434171?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434189?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434411?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434556?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434594?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434595?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434611?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434617?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434618?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434620?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434623?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434630?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434631?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434706?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434707?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434708?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434709?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434710?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434711?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434712?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434713?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434714?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434715?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434716?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434719?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434720?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434721?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434722?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434725?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434726?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434727?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434728?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434729?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434730?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434735?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434736?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434741?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434749?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434758?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434759?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434770?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434771?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434772?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434773?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434774?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434775?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=434797?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435002?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435003?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435005?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435006?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435007?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435008?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435009?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435010?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435011?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435012?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435013?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435014?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435015?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435016?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435017?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435018?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435019?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435021?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435028?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435030?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435031?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435032?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435034?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435035?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435038?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435039?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435040?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435081?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435082?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435083?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435091?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435092?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435093?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435147?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435217?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435218?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435251?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435292?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435338?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435339?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435564?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=435579?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=440204?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=450003?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=450054?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=450130?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=450447?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=480037?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=480455?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=480456?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=480457?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496419?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496482?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496483?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496484?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496486?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496487?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496488?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496489?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496490?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496491?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496492?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496493?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496494?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496495?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496496?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496497?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=496498?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=702857?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=702904?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703619?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703644?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703656?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703670?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703679?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703689?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703694?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703711?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703725?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703831?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703840?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703850?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703866?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703873?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703890?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703892?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703941?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703951?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703976?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=703996?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719372?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719419?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719422?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719425?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719434?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719445?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719448?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719480?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719485?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719489?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719492?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=719499?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=725353?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=725366?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=738161?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=740716?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=746061?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=746362?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747025?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747026?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747027?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747028?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747029?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747030?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747031?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747032?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747033?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747034?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747035?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747036?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747037?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747038?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747039?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747040?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747041?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747042?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747043?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747044?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747046?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747048?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747049?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747199?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747201?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747202?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747204?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747205?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747206?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747208?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747209?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747210?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747211?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747212?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747216?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747800?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747801?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747802?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747803?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747804?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747805?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747806?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747807?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747808?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747809?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747810?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747811?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747812?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747813?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747814?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747815?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747816?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747817?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747818?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747819?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747820?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747821?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747822?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747824?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747825?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747826?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747827?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747828?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747829?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747830?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747831?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747832?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747833?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747834?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747835?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747841?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747842?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747843?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747844?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747845?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747846?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747847?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747848?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747849?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747850?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747851?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747852?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747853?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747854?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747855?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747856?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747857?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747858?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747859?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747860?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747861?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747862?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747863?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747864?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747865?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747866?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747867?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747868?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747869?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747870?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747871?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747872?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747901?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747908?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747909?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747913?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747916?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747917?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747920?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747924?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747925?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747928?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747929?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747932?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747933?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747936?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747940?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747941?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747944?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747945?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747948?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747949?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747952?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747953?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747956?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747957?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747960?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747961?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747964?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747965?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747968?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747969?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747972?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747973?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747976?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747977?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747980?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747981?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747984?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747985?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747988?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747989?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747992?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747993?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747996?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=747997?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748000?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748004?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748005?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748008?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748009?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=748012?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=SW132477?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=082209?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=137994?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749901?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749904?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749905?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749906?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749908?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749915?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749920?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749921?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749922?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=749923?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=750000?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=966905?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=966906?reference=PartSearchListLink',
'https://dodge.ptplace.com/productDetail/_pn=966907?reference=PartSearchListLink']

for row in myresult:

 try:

    product_url = row

    #page = requests.get(product_url)

    headers = {"User-Agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)", "Referer": "http://example.com"}

    result = requests.get(product_url, headers=headers)

    if result.status_code == 200:

        print("site woking")

    else:

        print("site not working"+str(result.status_code))

    #a = (result.content.decode())


    soup = BeautifulSoup(result.content,'html.parser')

    #print(soup.prettify())





    bread = soup.find("ol",class_="breadcrumb pb-0 mb-0 px-0 pt-3 pt-md-0").find_all("li")
    list1 = []
    for b in bread:
        list1.append(b.text.strip())
    print(list1)





    # qnt = (soup.prettify().replace('data-ship-pack-quantity="', "raptor:").split("raptor:")[1].split('"')[0])

    #weight = soup.find("div",class_="rta sidebar__shipping-pane")



    #detail = soup.find("div",class_="copyTextSection textSection")
    #image enhanced-content__carousel-main-image image--loaded
    #soup.find("span",attrs={'data-automated-test':'leaf'})


    c = (product_url)
    print(c)



    # zxqw = qnt
    #https://static.grainger.com/rp/s/is/image/Grainger/29DJ11_GC01?hei=804&wid=804
    try:


     prod = soup.find_all("bdo",class_="data-label text-uppercase text-transparent-dark")


     specs = soup.find_all("td",class_="w-50 bg-white css-k6e94w ewehtpn0")



     i = 0
    except:
        pass
    if(len(prod)>0):

     while i < len(prod):


        j = 0

        while j < len(specs):

            z = (prod[i].text if prod else "not given")
            print(z)

            i += 1

            x = (specs[j].text if specs else "not given")
            print(x)

            j += 1
            save_details: TextIO = open("dodge-1111.txt", "a+", encoding="utf-8")
            save_details.write("\n"+c+"\t"+" / ".join(list1)+"\t"+"RP_"+z+"\t"+"RP_"+x)
            save_details.close()
            print("\n**Record stored into txt file.**")
    else:
        save_details: TextIO = open("dodge-1111.txt", "a+", encoding="utf-8")
        save_details.write("\n" + c + "\t" + " / ".join(list1))
        save_details.close()
        print("\n**Record stored into txt file.**")





 except AttributeError:

   pass
