import requests
from bs4 import BeautifulSoup
from typing import TextIO
import re


myresult=['https://www.vestil.com/sku.php?Model=D-100-HD-BG',
'https://www.vestil.com/sku.php?Model=D-100-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-100-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-100-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-100-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-100-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-100-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-100-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-100-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-100-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-100-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-100-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-100-HD-SL',
'https://www.vestil.com/sku.php?Model=D-100-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-100-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-100-LD-BG',
'https://www.vestil.com/sku.php?Model=D-100-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-100-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-100-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-100-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-100-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-100-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-100-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-100-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-100-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-100-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-100-LD-SL',
'https://www.vestil.com/sku.php?Model=D-100-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-100-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-100-MD-BG',
'https://www.vestil.com/sku.php?Model=D-100-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-100-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-100-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-100-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-100-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-100-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-100-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-100-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-100-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-100-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-100-MD-SL',
'https://www.vestil.com/sku.php?Model=D-100-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-100-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-150-HD-BG',
'https://www.vestil.com/sku.php?Model=D-150-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-150-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-150-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-150-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-150-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-150-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-150-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-150-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-150-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-150-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-150-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-150-HD-SL',
'https://www.vestil.com/sku.php?Model=D-150-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-150-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-150-LD-BG',
'https://www.vestil.com/sku.php?Model=D-150-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-150-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-150-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-150-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-150-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-150-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-150-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-150-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-150-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-150-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-150-LD-SL',
'https://www.vestil.com/sku.php?Model=D-150-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-150-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-150-MD-BG',
'https://www.vestil.com/sku.php?Model=D-150-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-150-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-150-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-150-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-150-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-150-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-150-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-150-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-150-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-150-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-150-MD-SL',
'https://www.vestil.com/sku.php?Model=D-150-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-150-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-200-HD-BG',
'https://www.vestil.com/sku.php?Model=D-200-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-200-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-200-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-200-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-200-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-200-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-200-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-200-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-200-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-200-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-200-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-200-HD-SL',
'https://www.vestil.com/sku.php?Model=D-200-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-200-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-200-LD-BG',
'https://www.vestil.com/sku.php?Model=D-200-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-200-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-200-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-200-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-200-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-200-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-200-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-200-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-200-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-200-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-200-LD-SL',
'https://www.vestil.com/sku.php?Model=D-200-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-200-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-200-MD-BG',
'https://www.vestil.com/sku.php?Model=D-200-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-200-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-200-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-200-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-200-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-200-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-200-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-200-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-200-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-200-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-200-MD-SL',
'https://www.vestil.com/sku.php?Model=D-200-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-200-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-250-HD-BG',
'https://www.vestil.com/sku.php?Model=D-250-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-250-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-250-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-250-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-250-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-250-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-250-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-250-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-250-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-250-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-250-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-250-HD-SL',
'https://www.vestil.com/sku.php?Model=D-250-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-250-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-250-LD-BG',
'https://www.vestil.com/sku.php?Model=D-250-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-250-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-250-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-250-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-250-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-250-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-250-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-250-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-250-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-250-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-250-LD-SL',
'https://www.vestil.com/sku.php?Model=D-250-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-250-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-250-MD-BG',
'https://www.vestil.com/sku.php?Model=D-250-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-250-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-250-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-250-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-250-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-250-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-250-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-250-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-250-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-250-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-250-MD-SL',
'https://www.vestil.com/sku.php?Model=D-250-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-250-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-25-HD-BG',
'https://www.vestil.com/sku.php?Model=D-25-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-25-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-25-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-25-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-25-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-25-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-25-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-25-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-25-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-25-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-25-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-25-HD-SL',
'https://www.vestil.com/sku.php?Model=D-25-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-25-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-25-LD-BG',
'https://www.vestil.com/sku.php?Model=D-25-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-25-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-25-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-25-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-25-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-25-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-25-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-25-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-25-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-25-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-25-LD-SL',
'https://www.vestil.com/sku.php?Model=D-25-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-25-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-25-MD-BG',
'https://www.vestil.com/sku.php?Model=D-25-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-25-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-25-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-25-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-25-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-25-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-25-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-25-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-25-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-25-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-25-MD-SL',
'https://www.vestil.com/sku.php?Model=D-25-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-25-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-300-HD-BG',
'https://www.vestil.com/sku.php?Model=D-300-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-300-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-300-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-300-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-300-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-300-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-300-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-300-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-300-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-300-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-300-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-300-HD-SL',
'https://www.vestil.com/sku.php?Model=D-300-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-300-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-300-LD-BG',
'https://www.vestil.com/sku.php?Model=D-300-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-300-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-300-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-300-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-300-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-300-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-300-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-300-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-300-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-300-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-300-LD-SL',
'https://www.vestil.com/sku.php?Model=D-300-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-300-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-300-MD-BG',
'https://www.vestil.com/sku.php?Model=D-300-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-300-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-300-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-300-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-300-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-300-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-300-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-300-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-300-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-300-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-300-MD-SL',
'https://www.vestil.com/sku.php?Model=D-300-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-300-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-33-HD-BG',
'https://www.vestil.com/sku.php?Model=D-33-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-33-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-33-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-33-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-33-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-33-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-33-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-33-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-33-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-33-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-33-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-33-HD-SL',
'https://www.vestil.com/sku.php?Model=D-33-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-33-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-33-LD-BG',
'https://www.vestil.com/sku.php?Model=D-33-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-33-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-33-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-33-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-33-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-33-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-33-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-33-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-33-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-33-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-33-LD-SL',
'https://www.vestil.com/sku.php?Model=D-33-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-33-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-33-MD-BG',
'https://www.vestil.com/sku.php?Model=D-33-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-33-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-33-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-33-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-33-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-33-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-33-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-33-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-33-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-33-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-33-MD-SL',
'https://www.vestil.com/sku.php?Model=D-33-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-33-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-50-HD-BG',
'https://www.vestil.com/sku.php?Model=D-50-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-50-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-50-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-50-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-50-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-50-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-50-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-50-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-50-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-50-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-50-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-50-HD-SL',
'https://www.vestil.com/sku.php?Model=D-50-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-50-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-50-LD-BG',
'https://www.vestil.com/sku.php?Model=D-50-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-50-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-50-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-50-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-50-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-50-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-50-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-50-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-50-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-50-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-50-LD-SL',
'https://www.vestil.com/sku.php?Model=D-50-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-50-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-50-MD-BG',
'https://www.vestil.com/sku.php?Model=D-50-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-50-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-50-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-50-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-50-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-50-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-50-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-50-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-50-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-50-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-50-MD-SL',
'https://www.vestil.com/sku.php?Model=D-50-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-50-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-75-HD-BG',
'https://www.vestil.com/sku.php?Model=D-75-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-75-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-75-HD-BL-S',
'https://www.vestil.com/sku.php?Model=D-75-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-75-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-75-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-75-HD-GAL',
'https://www.vestil.com/sku.php?Model=D-75-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-75-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-75-HD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-75-HD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-75-HD-SL',
'https://www.vestil.com/sku.php?Model=D-75-HD-WHT',
'https://www.vestil.com/sku.php?Model=D-75-HD-YEL',
'https://www.vestil.com/sku.php?Model=D-75-LD-BG',
'https://www.vestil.com/sku.php?Model=D-75-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-75-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-75-LD-BL-S',
'https://www.vestil.com/sku.php?Model=D-75-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-75-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-75-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-75-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-75-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-75-LD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-75-LD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-75-LD-SL',
'https://www.vestil.com/sku.php?Model=D-75-LD-WHT',
'https://www.vestil.com/sku.php?Model=D-75-LD-YEL',
'https://www.vestil.com/sku.php?Model=D-75-MD-BG',
'https://www.vestil.com/sku.php?Model=D-75-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=D-75-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=D-75-MD-BL-S',
'https://www.vestil.com/sku.php?Model=D-75-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=D-75-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=D-75-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=D-75-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=D-75-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=D-75-MD-GY-SG',
'https://www.vestil.com/sku.php?Model=D-75-MD-ORG-C',
'https://www.vestil.com/sku.php?Model=D-75-MD-SL',
'https://www.vestil.com/sku.php?Model=D-75-MD-WHT',
'https://www.vestil.com/sku.php?Model=D-75-MD-YEL',
'https://www.vestil.com/sku.php?Model=D-DPLG-75',
'https://www.vestil.com/sku.php?Model=EHLT-10-43',
'https://www.vestil.com/sku.php?Model=EHLT-10-55',
'https://www.vestil.com/sku.php?Model=EHLT-10-72',
'https://www.vestil.com/sku.php?Model=EHLT-12-43',
'https://www.vestil.com/sku.php?Model=EHLT-12-55',
'https://www.vestil.com/sku.php?Model=EHLT-12-72',
'https://www.vestil.com/sku.php?Model=EHLT-1-43',
'https://www.vestil.com/sku.php?Model=EHLT-1-43-PSS',
'https://www.vestil.com/sku.php?Model=EHLT-1-55',
'https://www.vestil.com/sku.php?Model=EHLT-1-67',
'https://www.vestil.com/sku.php?Model=EHLT-1-79',
'https://www.vestil.com/sku.php?Model=EHLT-2-43',
'https://www.vestil.com/sku.php?Model=EHLT-2-43-PSS',
'https://www.vestil.com/sku.php?Model=EHLT-2-55',
'https://www.vestil.com/sku.php?Model=EHLT-2-67',
'https://www.vestil.com/sku.php?Model=EHLT-2-79',
'https://www.vestil.com/sku.php?Model=EHLT-3-43',
'https://www.vestil.com/sku.php?Model=EHLT-3-43-PSS',
'https://www.vestil.com/sku.php?Model=EHLT-3-55',
'https://www.vestil.com/sku.php?Model=EHLT-3-67',
'https://www.vestil.com/sku.php?Model=EHLT-3-82',
'https://www.vestil.com/sku.php?Model=EHLT-4-43',
'https://www.vestil.com/sku.php?Model=EHLT-4-43-PSS',
'https://www.vestil.com/sku.php?Model=EHLT-4-56',
'https://www.vestil.com/sku.php?Model=EHLT-4-68',
'https://www.vestil.com/sku.php?Model=EHLT-4-82',
'https://www.vestil.com/sku.php?Model=EHLT-4864-3-55',
'https://www.vestil.com/sku.php?Model=EHLT-4884-3-67',
'https://www.vestil.com/sku.php?Model=EHLT-5-44',
'https://www.vestil.com/sku.php?Model=EHLT-5-56',
'https://www.vestil.com/sku.php?Model=EHLT-5-68',
'https://www.vestil.com/sku.php?Model=EHLT-5-82',
'https://www.vestil.com/sku.php?Model=EHLT-6-44',
'https://www.vestil.com/sku.php?Model=EHLT-6-56',
'https://www.vestil.com/sku.php?Model=EHLT-6-70',
'https://www.vestil.com/sku.php?Model=EHLT-6-82',
'https://www.vestil.com/sku.php?Model=EHLT-8-44',
'https://www.vestil.com/sku.php?Model=EHLT-8-56',
'https://www.vestil.com/sku.php?Model=EHLT-8-70',
'https://www.vestil.com/sku.php?Model=EHLT-8-82',
'https://www.vestil.com/sku.php?Model=FL-LEKP',
'https://www.vestil.com/sku.php?Model=H-100-HD-BG',
'https://www.vestil.com/sku.php?Model=H-100-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-100-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-100-HD-BL-S',
'https://www.vestil.com/sku.php?Model=H-100-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-100-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-100-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-100-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-100-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-100-HD-SL',
'https://www.vestil.com/sku.php?Model=H-100-LD-BG',
'https://www.vestil.com/sku.php?Model=H-100-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-100-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-100-LD-BL-S',
'https://www.vestil.com/sku.php?Model=H-100-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-100-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-100-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-100-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-100-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-100-LD-SL',
'https://www.vestil.com/sku.php?Model=H-100-MD-BG',
'https://www.vestil.com/sku.php?Model=H-100-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-100-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-100-MD-BL-S',
'https://www.vestil.com/sku.php?Model=H-100-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-100-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-100-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-100-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-100-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-100-MD-SL',
'https://www.vestil.com/sku.php?Model=H-150-HD-BG',
'https://www.vestil.com/sku.php?Model=H-150-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-150-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-150-HD-BL-S',
'https://www.vestil.com/sku.php?Model=H-150-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-150-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-150-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-150-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-150-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-150-HD-SL',
'https://www.vestil.com/sku.php?Model=H-150-LD-BG',
'https://www.vestil.com/sku.php?Model=H-150-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-150-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-150-LD-BL-S',
'https://www.vestil.com/sku.php?Model=H-150-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-150-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-150-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-150-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-150-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-150-LD-SL',
'https://www.vestil.com/sku.php?Model=H-150-MD-BG',
'https://www.vestil.com/sku.php?Model=H-150-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-150-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-150-MD-BL-S',
'https://www.vestil.com/sku.php?Model=H-150-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-150-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-150-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-150-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-150-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-150-MD-SL',
'https://www.vestil.com/sku.php?Model=H-25-HD-BG',
'https://www.vestil.com/sku.php?Model=H-25-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-25-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-25-HD-BL-S',
'https://www.vestil.com/sku.php?Model=H-25-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-25-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-25-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-25-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-25-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-25-HD-SL',
'https://www.vestil.com/sku.php?Model=H-25-LD-BG',
'https://www.vestil.com/sku.php?Model=H-25-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-25-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-25-LD-BL-S',
'https://www.vestil.com/sku.php?Model=H-25-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-25-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-25-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-25-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-25-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-25-LD-SL',
'https://www.vestil.com/sku.php?Model=H-25-MD-BG',
'https://www.vestil.com/sku.php?Model=H-25-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-25-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-25-MD-BL-S',
'https://www.vestil.com/sku.php?Model=H-25-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-25-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-25-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-25-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-25-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-25-MD-SL',
'https://www.vestil.com/sku.php?Model=H-50-HD-BG',
'https://www.vestil.com/sku.php?Model=H-50-HD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-50-HD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-50-HD-BL-S',
'https://www.vestil.com/sku.php?Model=H-50-HD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-50-HD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-50-HD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-50-HD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-50-HD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-50-HD-SL',
'https://www.vestil.com/sku.php?Model=H-50-LD-BG',
'https://www.vestil.com/sku.php?Model=H-50-LD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-50-LD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-50-LD-BL-S',
'https://www.vestil.com/sku.php?Model=H-50-LD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-50-LD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-50-LD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-50-LD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-50-LD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-50-LD-SL',
'https://www.vestil.com/sku.php?Model=H-50-MD-BG',
'https://www.vestil.com/sku.php?Model=H-50-MD-BLK-HG',
'https://www.vestil.com/sku.php?Model=H-50-MD-BLK-SG',
'https://www.vestil.com/sku.php?Model=H-50-MD-BL-S',
'https://www.vestil.com/sku.php?Model=H-50-MD-BRN-EB',
'https://www.vestil.com/sku.php?Model=H-50-MD-BRN-KT',
'https://www.vestil.com/sku.php?Model=H-50-MD-BRN-SB',
'https://www.vestil.com/sku.php?Model=H-50-MD-GRN-H',
'https://www.vestil.com/sku.php?Model=H-50-MD-GY-MG',
'https://www.vestil.com/sku.php?Model=H-50-MD-SL',
'https://www.vestil.com/sku.php?Model=HBD-PU-X',
'https://www.vestil.com/sku.php?Model=H-DPLG-2',
'https://www.vestil.com/sku.php?Model=H-DPLG-75',
'https://www.vestil.com/sku.php?Model=HOP-CASTER-BASE',
'https://www.vestil.com/sku.php?Model=HYDC-BTP',
'https://www.vestil.com/sku.php?Model=HYDC-DSPIN',
'https://www.vestil.com/sku.php?Model=HYDC-FRKHK',
'https://www.vestil.com/sku.php?Model=LUG',
'https://www.vestil.com/sku.php?Model=S-CB-62-DDC',
'https://www.vestil.com/sku.php?Model=UNI-2448-2',
'https://www.vestil.com/sku.php?Model=UNI-4048-2',
'https://www.vestil.com/sku.php?Model=UNI-4048-2-YEL',
'https://www.vestil.com/sku.php?Model=UNI-4048-4',
'https://www.vestil.com/sku.php?Model=UNI-4048-4-YEL',
'https://www.vestil.com/sku.php?Model=UNI-4848-2',
'https://www.vestil.com/sku.php?Model=UNI-5448-2',
'https://www.vestil.com/sku.php?Model=HYDC-RP',
'https://www.vestil.com/sku.php?Model=HYDC-RR',
'https://www.vestil.com/sku.php?Model=HYDC-SPIN',
'https://www.vestil.com/sku.php?Model=HYDC-SSP',
'https://www.vestil.com/sku.php?Model=HYDC-VBLK',
'https://www.vestil.com/sku.php?Model=HYDC-VFRK']
for row in myresult:
 try:

    product_url = row
    print(product_url)

    #page = requests.get(product_url)

    headers = {"User-Agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)", "Referer": "http://example.com"}

    result = requests.get(product_url, headers=headers)

    if result.status_code == 200:

        print("site woking")

    else:

        print("site not working"+str(result.status_code))

    #a = (result.content.decode())


    soup = BeautifulSoup(result.content,'html.parser')

    #print(soup.prettify())

    title = soup.find("div",class_="heading-title heading-dotted text-center")
    a = (title.text.strip() if title else "not given")
    print(a)
    a=a.split(":")[1]
    a=a.split()
    print(a)






    brand = soup.find("h2")



    image = soup.find("img",attrs={'alt':a})

    y = (image.get("src") if image else "not given")
    print(y)

    c = (product_url)
    print(c)

    d = (brand.text.strip() if brand else "not given")
    print(d)
    pd = soup.find_all("a", attrs={'data-toggle': 'tooltip'})
    listp=[]
    for p in pd:
     pp = (p.get("href") if p else "not given")
     listp.append(pp)
     print(pp)



    prod = soup.find_all("strong",class_="text-primary")

    specs = soup.find_all("div",class_="col-8 text-left")

    i = 0

    while i < len(prod):

        j = 0

        while j < len(specs):

            z = (prod[i].text if prod else "not given")
            print(z)

            i += 1

            x = (specs[j].text if specs else "not given")
            print(x)

            j += 1
            save_details: TextIO = open("vestil_raghav.txt", "a+", encoding="utf-8")
            save_details.write("\n"+str(a)+"\t"+d+"\t"+c+"\t"+y+"\t"+" , ".join(listp)+"\t"+"RP_"+z+"\t"+"RP_"+x)
            save_details.close()
            print("\n**Record stored into txt file.**")






 except AttributeError:

   pass
