import requests
from bs4 import BeautifulSoup
import time
from typing import TextIO
# import mysql.connector
#
# mydb = mysql.connector.connect(
#     host="rpt-m24-development.c5tedj3txtxy.eu-west-1.rds.amazonaws.com",
#     user="raptoradmin",
#     passwd="Raptorpwa2020",
#     database='ansu_data_check'
# )
# mycursor = mydb.cursor()
myresults=[
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=187',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=188',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=189',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=190',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=191',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=192',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=193',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=194',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=195',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=196',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=197',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=198',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=199',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=200',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=201',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=202',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=203',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=204',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=205',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=206',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=207',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=208',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=209',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=210',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=211',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=212',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=213',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=214',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=215',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=216',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=217',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=218',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=219',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=220',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=221',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=222',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=223',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=224',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=225',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=226',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=227',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=228',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=229',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=230',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=231',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=232',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=233',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=234',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=235',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=236',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=237',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=238',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=239',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=240',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=241',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=242',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=243',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=244',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=245',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=246',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=247',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=248',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=249',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=250',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=251',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=252',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=253',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=254',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=255',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=256',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=257',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=258',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=259',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=260',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=261',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=262',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=263',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=264',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=265',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=266',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=267',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=268',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=269',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=270',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=271',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=272',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=273',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=274',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=275',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=276',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=277',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=278',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=279',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=280',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=281',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=282',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=283',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=284',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=285',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=286',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=287',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=288',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=289',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=290',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=291',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=292',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=293',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=294',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=295',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=296',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=297',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=298',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=299',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=300',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=301',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=302',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=303',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=304',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=305',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=306',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=307',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=308',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=309',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=310',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=311',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=312',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=313',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=314',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=315',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=316',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=317',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=318',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=319',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=320',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=321',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=322',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=323',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=324',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=325',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=326',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=327',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=328',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=329',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=330',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=331',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=332',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=333',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=334',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=335',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=336',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=337',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=338',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=339',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=340',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=341',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=342',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=343',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=344',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=345',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=346',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=347',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=348',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=349',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=350',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=351',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=352',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=353',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=354',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=355',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=356',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=357',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=358',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=359',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=360',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=361',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=362',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=363',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=364',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=365',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=366',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=367',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=368',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=369',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=370',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=371',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=372',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=373',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=374',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=375',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=376',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=377',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=378',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=379',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=380',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=381',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=382',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=383',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=384',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=385',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=386',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=387',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=388',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=389',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=390',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=391',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=392',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=393',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=394',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=395',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=396',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=397',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=398',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=399',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=400',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=401',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=402',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=403',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=404',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=405',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=406',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=407',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=408',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=409',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=410',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=411',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=412',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=413',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=414',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=415',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=416',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=417',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=418',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=419',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=420',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=421',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=422',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=423',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=424',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=425',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=426',
'https://www.gordonelectricsupply.com/s/Appleton-Electric/mfr-1ICG?process=search&itemsperpage=60&sortby=availSort&display=thumb&fqall=&fqv=&fq=&sf=&allnstr=&ph=&pl=&qdx=0&nstr=&narrowby=&pagenum=427']
a = 0
for result in myresults:
    a += 1
    print(a)
    try:
        url = result
        reqs = requests.get(url)
        soup = BeautifulSoup(reqs.text, 'lxml')
        time.sleep(3)
        url_lst1 = []
        for s in soup.find_all('a', {'class': 'prodTitle'}):
            prod_url = s['href']
            print(prod_url)
            save_details: TextIO = open("gordon.txt", "a+", encoding="utf-8")
            save_details.write("\n" + prod_url)
            save_details.close()
            print("\n**Record stored into txt file.**")


    except AttributeError:
        pass
