import time
from selenium import webdriver
from selenium.webdriver.common.by import By
import pyautogui
import os
driver = webdriver.Chrome('C:/Users/hp/Downloads/chromedriver_win32 (1)//chromedriver.exe')

url = ['https://s5.raptorsupplies.co.uk/vendor-registration',
       'https://s5.raptorsupplies.co.uk/request-for-quote',
       'https://s5.raptorsupplies.co.uk/source',
       'https://s5.raptorsupplies.co.uk/credit-account-application',
       'https://s5.raptorsupplies.co.uk/submit-purchase-order',
       'https://s5.raptorsupplies.co.uk/grainger-uk-dealer',
       'https://s5.raptorsupplies.co.uk/b/mcmaster-carr-europe-uk-distributor',
       'https://s5.raptorsupplies.co.uk/contact'
       ]
name, email, p_no, comment = 'Rahul Kumar Singh', 'rksingh@nextgenesolutions.com', '8294966962', 'automated test by rahul'
interest = 'checking purpose'
# print(name)
a = 0
for fetch in url:
    a += 1
    if a == 1:
        print('vendor-registration check start:')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'name').send_keys(name)
        driver.find_element(By.ID, 'email').send_keys(email)
        driver.find_element(By.ID, 'phone').send_keys(p_no)
        driver.find_element(By.ID, 'company').send_keys(comment)
        driver.find_element(By.XPATH, '//*[@id="vendor_contact_form"]/button').click()
        time.sleep(3)
        demo_div = driver.find_element(By.XPATH, '//*[@id="show_success_msg_rfq"]').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        print('----vendor-registration complete---')
    elif a == 2:
        print('request-for-quote check start:')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'name').send_keys(name)
        driver.find_element(By.ID, 'emailform').send_keys(email)
        driver.find_element(By.ID, 'phoneform').send_keys(p_no)
        driver.find_element(By.ID, 'interest').send_keys(interest)
        driver.find_element(By.ID, 'message').send_keys('automated test by rahul')
        driver.find_element(By.XPATH, '//*[@id="mro_form"]/button').click()
        time.sleep(3)
        demo_div = driver.find_element(By.XPATH, '//*[@id="mro_form"]/div[1]').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        time.sleep(2)
        print('---request-for-quote complete---')
    elif a == 3:
        print('source check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'img-form-name').send_keys(name)
        driver.find_element(By.ID, 'img-form-email').send_keys(email)
        driver.find_element(By.ID, 'document_upload').send_keys('C://Users/hp/PycharmProjects/demo_script/img3.jpg')
        driver.find_element(By.ID, 'cmnt').send_keys(comment)
        driver.find_element(By.XPATH, '//*[@id="ksb_but"]').click()
        # demo_div = driver.find_element(By.ID, 'show_success_msg').find_element(By.TAG_NAME, 'p')
        # s = (demo_div.get_attribute('textContent'))
        # print(s)
        time.sleep(2)
        print("---product---")
    elif a == 4:
        print('credit-account-application check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'company_name').send_keys(name)
        driver.find_element(By.ID, 'email').send_keys(email)
        driver.find_element(By.ID, 'phone').send_keys(p_no)
        driver.find_element(By.ID, 'credit_limit').send_keys('1')
        time.sleep(1)
        driver.find_element(By.ID, 'full_company_name').send_keys('nxt raptor')
        driver.find_element(By.ID, 'company_registration').send_keys('12345')
        driver.find_element(By.ID, 'vat').send_keys('12345')
        driver.find_element(By.ID, 'country_finanace_account_payable_email_address').send_keys('rksingh@nextgenesolutions.com')
        time.sleep(2)
        driver.find_element(By.ID, 'address1').send_keys('mohan estate')
        driver.find_element(By.ID, 'address2').send_keys('sarita vihar')
        driver.find_element(By.ID, 'town_city').send_keys('new delhi')
        driver.find_element(By.ID, 'postcode').send_keys('110076')
        driver.find_element(By.XPATH, '//*[@id="checkedtc"]').click()
        time.sleep(2)
        driver.find_element(By.ID, 'submit').click()
        time.sleep(3)
        demo_div = driver.find_element(By.ID, 'show_success_msg').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        time.sleep(2)
        print('---credit-account-application check start----')
    elif a == 5:
        print('submit-purchase-order check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'name').send_keys(name)
        driver.find_element(By.ID, 'uemail').send_keys(email)
        driver.find_element(By.ID, 'uphone').send_keys(p_no)
        driver.find_element(By.ID, 'fileUpload').send_keys('C://Users/hp/PycharmProjects/demo_script/img3.jpg')
        driver.find_element(By.ID, 'ksb_but').click()
        time.sleep(3)
        demo_div = driver.find_element(By.ID, 'show_success_msg').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        time.sleep(2)
        print('---submit-purchase-order---')
    elif a == 6:
        print('grainger-uk-dealer check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'name').send_keys(name)
        driver.find_element(By.ID, 'email_id').send_keys(email)
        driver.find_element(By.ID, 'phone_num').send_keys(p_no)
        driver.find_element(By.ID, 'partnumber').send_keys('12345')
        driver.find_element(By.ID, 'qty').send_keys('12')
        driver.find_element(By.ID, 'cmnt').send_keys(comment)
        driver.find_element(By.XPATH, '//*[@id="mcmaster_enquiry"]/button').send_keys('\n')
        time.sleep(3)
        demo_div = driver.find_element(By.XPATH, '//*[@id="flash-msg-mcmaster"]').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        time.sleep(2)
        print('---grainger-uk-dealer---')
    elif a == 7:
        print('mcmaster-carr-europe-uk-distributor check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(5)
        driver.find_element(By.ID, 'name').send_keys(name)
        driver.find_element(By.ID, 'email_id').send_keys(email)
        driver.find_element(By.ID, 'partnumber').send_keys('1234')
        driver.find_element(By.ID, 'qty').send_keys('12')
        driver.find_element(By.ID, 'addcmmnt').click()
        driver.find_element(By.ID, 'cmnt').send_keys(comment)
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="mcmaster_enquiry"]/div[6]/button').send_keys("\n")
        time.sleep(3)
        demo_div = driver.find_element(By.XPATH, '//*[@id="flash-msg-mcmaster"]').find_element(By.TAG_NAME, 'p')
        s = (demo_div.get_attribute('textContent'))
        print(s)
        time.sleep(2)
        print('---mcmaster-carr-europe-uk-distributor---')
    elif a == 8:
        print('contact us check start')
        driver.get(fetch)
        driver.maximize_window()
        time.sleep(3)
        driver.find_element(By.XPATH, '//*[@id="file-upload"]').send_keys("C://Users/hp/PycharmProjects/demo_script/img3.jpg")
        driver.find_element(By.ID, 'img-form-name').send_keys(name)
        driver.find_element(By.ID, 'img-form-email').send_keys(email)
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="ksb_but"]').send_keys('\n')
        time.sleep(2)
        # demo_div = driver.find_element(By.ID, 'show_success_msg').find_element(By.TAG_NAME, 'p')
        # s = (demo_div.get_attribute('textContent'))
        # print(s)
        time.sleep(2)
        print('---contact us complete---')
    else:
        print('url not working')

driver.close()
print("driver successfully close")
