import urllib.parse
from datetime import datetime
from typing import TextIO
from selenium import webdriver
import time
import sys
from selenium.webdriver.chrome.options import Options
import selenium.webdriver.remote.webelement


def get_details(url):
    global d
    #current_date: object = datetime.now()
    #save_details: TextIO = open("Destacoo.txt", "a+")
    #save_details.write("\nScrapping Started at : " + current_date.strftime("%B %d, %Y - %H:%M:%S") + "\n")
    #save_details.close()
    #print("\nScrapping Started at : " + current_date.strftime("%B %d, %Y - %H:%M:%S") + "\n")

    print("Please wait. Program will work in background.\n")

    chrome_options = Options()
    chrome_options.add_argument("--headless")
    d = webdriver.Chrome("C:/chromedriver.exe", options=chrome_options)
    d.get(url)
    time.sleep(5)

    try:



            product_name1 =att1=val1 = product_details = uses = use = table1 = image  = model = our_model = upc = condition= breakups=''

            print("\n----------------------------------------------------------\n")

            try:
                product_name1=d.find_element_by_xpath("/html/body/section[3]/div/div[2]/div[2]/h1").text
                print("product_name_1 :"+ product_name1)
            except:
                pass
            try:
                breakups=d.find_element_by_xpath("/html/body/section[2]/div/ul").text
                print("breakups :"+ breakups)
            except:
                pass



            try:
                product_details=d.find_element_by_xpath("/html/body/section[4]/div/div/div[2]/div/p[1]").text
                print("product details :"+product_details)
            except:
                pass



            try:
                uses=d.find_element_by_xpath("/html/body/section[4]/div/div/div[2]/div/p[2]").text
                print("uses :"+uses)
            except:
                pass

            try:
                use = d.find_element_by_xpath("/html/body/section[4]/div/div/div[2]/div/ul[1]/li").text
                print("uses :" + use)
            except:
                pass


            for i in range(1,20):
             try:
                att1=d.find_element_by_xpath("/html/body/section[4]/div/div/div[1]/table[1]/tbody/tr["+str(i)+"]/td[1]").text
                print(att1)
                val1=d.find_element_by_xpath("/html/body/section[4]/div/div/div[1]/table[1]/tbody/tr["+str(i)+"]/td[2]").text
                print(val1)
                save_details: TextIO = open("Destaco(DE).txt", "a+", encoding="utf-8")
                save_details.write("\n" + list[x] + "\t" + product_name1 +"\t"+ breakups+ "\t" + product_details + "\t" + uses + "\t" + use +"\t"+att1+"\t"+val1)
                save_details.close()
                print("\n**Record stored into txt file.**")

             except:
                pass





    except:

            d.close()


















if __name__ == '__main__':

     list =['https://www.raptorsupplies.de/pd/destaco/205-sss',
'https://www.raptorsupplies.de/pd/destaco/307-u',
'https://www.raptorsupplies.de/pd/destaco/309-u',
'https://www.raptorsupplies.de/pd/destaco/305-uss',
'https://www.raptorsupplies.de/pd/destaco/307-uss',
'https://www.raptorsupplies.de/pd/destaco/309-uss',
'https://www.raptorsupplies.de/pd/destaco/305-ur',
'https://www.raptorsupplies.de/pd/destaco/307-ur',
'https://www.raptorsupplies.de/pd/destaco/309-ur',
'https://www.raptorsupplies.de/pd/destaco/105208',
'https://www.raptorsupplies.de/pd/destaco/201208',
'https://www.raptorsupplies.de/pd/destaco/202208',
'https://www.raptorsupplies.de/pd/destaco/215208',
'https://www.raptorsupplies.de/pd/destaco/225208',
'https://www.raptorsupplies.de/pd/destaco/235208',
'https://www.raptorsupplies.de/pd/destaco/240208',
'https://www.raptorsupplies.de/pd/destaco/247208',
'https://www.raptorsupplies.de/pd/destaco/267208',
'https://www.raptorsupplies.de/pd/destaco/507208',
'https://www.raptorsupplies.de/pd/destaco/527208',
'https://www.raptorsupplies.de/pd/destaco/202208-m',
'https://www.raptorsupplies.de/pd/destaco/215208-m',
'https://www.raptorsupplies.de/pd/destaco/225208-m',
'https://www.raptorsupplies.de/pd/destaco/240208-m',
'https://www.raptorsupplies.de/pd/destaco/507208-m',
'https://www.raptorsupplies.de/pd/destaco/317-u',
'https://www.raptorsupplies.de/pd/destaco/205-s',
'https://www.raptorsupplies.de/pd/destaco/205-u',
'https://www.raptorsupplies.de/pd/destaco/213-u',
'https://www.raptorsupplies.de/pd/destaco/215-u',
'https://www.raptorsupplies.de/pd/destaco/217-u',
'https://www.raptorsupplies.de/pd/destaco/225-u',
'https://www.raptorsupplies.de/pd/destaco/227-u',
'https://www.raptorsupplies.de/pd/destaco/235-u',
'https://www.raptorsupplies.de/pd/destaco/237-u',
'https://www.raptorsupplies.de/pd/destaco/205-uss',
'https://www.raptorsupplies.de/pd/destaco/206-ss',
'https://www.raptorsupplies.de/pd/destaco/213-uss',
'https://www.raptorsupplies.de/pd/destaco/215-uss',
'https://www.raptorsupplies.de/pd/destaco/217-uss',
'https://www.raptorsupplies.de/pd/destaco/225-uss',
'https://www.raptorsupplies.de/pd/destaco/227-uss',
'https://www.raptorsupplies.de/pd/destaco/2013-ur',
'https://www.raptorsupplies.de/pd/destaco/2017-ur',
'https://www.raptorsupplies.de/pd/destaco/2027-ur',
'https://www.raptorsupplies.de/pd/destaco/225-ur',
'https://www.raptorsupplies.de/pd/destaco/235-ur',
'https://www.raptorsupplies.de/pd/destaco/301',
'https://www.raptorsupplies.de/pd/destaco/311',
'https://www.raptorsupplies.de/pd/destaco/330',
'https://www.raptorsupplies.de/pd/destaco/371',
'https://www.raptorsupplies.de/pd/destaco/375',
'https://www.raptorsupplies.de/pd/destaco/385',
'https://www.raptorsupplies.de/pd/destaco/323-ss',
'https://www.raptorsupplies.de/pd/destaco/331-ss',
'https://www.raptorsupplies.de/pd/destaco/341-ss',
'https://www.raptorsupplies.de/pd/destaco/330-ss',
'https://www.raptorsupplies.de/pd/destaco/331-rss',
'https://www.raptorsupplies.de/pd/destaco/341-rss',
'https://www.raptorsupplies.de/pd/destaco/324',
'https://www.raptorsupplies.de/pd/destaco/334',
'https://www.raptorsupplies.de/pd/destaco/344',
'https://www.raptorsupplies.de/pd/destaco/324-ss',
'https://www.raptorsupplies.de/pd/destaco/334-ss',
'https://www.raptorsupplies.de/pd/destaco/344-ss',
'https://www.raptorsupplies.de/pd/destaco/331-r',
'https://www.raptorsupplies.de/pd/destaco/341-r',
'https://www.raptorsupplies.de/pd/destaco/375-r',
'https://www.raptorsupplies.de/pd/destaco/385-r',
'https://www.raptorsupplies.de/pd/destaco/81l12-10100',
'https://www.raptorsupplies.de/pd/destaco/81l12-14100',
'https://www.raptorsupplies.de/pd/destaco/81l16-10100',
'https://www.raptorsupplies.de/pd/destaco/81l16-14100',
'https://www.raptorsupplies.de/pd/destaco/81l20-10100',
'https://www.raptorsupplies.de/pd/destaco/81l20-14100',
'https://www.raptorsupplies.de/pd/destaco/81l25-10100',
'https://www.raptorsupplies.de/pd/destaco/81l25-14100',
'https://www.raptorsupplies.de/pd/destaco/82l2g-2030000',
'https://www.raptorsupplies.de/pd/destaco/82l2g-203b800',
'https://www.raptorsupplies.de/pd/destaco/82l3g-2030000',
'https://www.raptorsupplies.de/pd/destaco/82l3g-203b800',
'https://www.raptorsupplies.de/pd/destaco/82l4g-2030000',
'https://www.raptorsupplies.de/pd/destaco/82l4g-203b800',
'https://www.raptorsupplies.de/pd/destaco/802-u',
'https://www.raptorsupplies.de/pd/destaco/807-u',
'https://www.raptorsupplies.de/pd/destaco/810-u',
'https://www.raptorsupplies.de/pd/destaco/812-u',
'https://www.raptorsupplies.de/pd/destaco/8021',
'https://www.raptorsupplies.de/pd/destaco/8071',
'https://www.raptorsupplies.de/pd/destaco/803',
'https://www.raptorsupplies.de/pd/destaco/830',
'https://www.raptorsupplies.de/pd/destaco/8031',
'https://www.raptorsupplies.de/pd/destaco/8015',
'https://www.raptorsupplies.de/pd/destaco/8016',
'https://www.raptorsupplies.de/pd/destaco/8115',
'https://www.raptorsupplies.de/pd/destaco/8116',
'https://www.raptorsupplies.de/pd/destaco/8215',
'https://www.raptorsupplies.de/pd/destaco/8216',
'https://www.raptorsupplies.de/pd/destaco/8315',
'https://www.raptorsupplies.de/pd/destaco/8316',
'https://www.raptorsupplies.de/pd/destaco/8415',
'https://www.raptorsupplies.de/pd/destaco/8416',
'https://www.raptorsupplies.de/pd/destaco/89r32-010-2',
'https://www.raptorsupplies.de/pd/destaco/89r40-010-2',
'https://www.raptorsupplies.de/pd/destaco/89r40-025-2',
'https://www.raptorsupplies.de/pd/destaco/89r50-025-2',
'https://www.raptorsupplies.de/pd/destaco/89r63-025-2',
'https://www.raptorsupplies.de/pd/destaco/9530-2l',
'https://www.raptorsupplies.de/pd/destaco/9530-2r',
'https://www.raptorsupplies.de/pd/destaco/9540-2l',
'https://www.raptorsupplies.de/pd/destaco/9540-2r',
'https://www.raptorsupplies.de/pd/destaco/9540150',
'https://www.raptorsupplies.de/pd/destaco/9540153',
'https://www.raptorsupplies.de/pd/destaco/8jg-215-1',
'https://www.raptorsupplies.de/pd/destaco/8jg-217-1',
'https://www.raptorsupplies.de/pd/destaco/8jg-218-1',
'https://www.raptorsupplies.de/pd/destaco/8jg-219-1',
'https://www.raptorsupplies.de/pd/destaco/8jg-220-1',
'https://www.raptorsupplies.de/pd/destaco/323',
'https://www.raptorsupplies.de/pd/destaco/331',
'https://www.raptorsupplies.de/pd/destaco/341',
'https://www.raptorsupplies.de/pd/destaco/351',
'https://www.raptorsupplies.de/pd/destaco/381',
'https://www.raptorsupplies.de/pd/destaco/351-ss',
'https://www.raptorsupplies.de/pd/destaco/325',
'https://www.raptorsupplies.de/pd/destaco/424',
'https://www.raptorsupplies.de/pd/destaco/441',
'https://www.raptorsupplies.de/pd/destaco/463',
'https://www.raptorsupplies.de/pd/destaco/482',
'https://www.raptorsupplies.de/pd/destaco/484',
'https://www.raptorsupplies.de/pd/destaco/325-ss',
'https://www.raptorsupplies.de/pd/destaco/607',
'https://www.raptorsupplies.de/pd/destaco/609',
'https://www.raptorsupplies.de/pd/destaco/650',
'https://www.raptorsupplies.de/pd/destaco/6015-m',
'https://www.raptorsupplies.de/pd/destaco/601',
'https://www.raptorsupplies.de/pd/destaco/603',
'https://www.raptorsupplies.de/pd/destaco/605',
'https://www.raptorsupplies.de/pd/destaco/608',
'https://www.raptorsupplies.de/pd/destaco/610',
'https://www.raptorsupplies.de/pd/destaco/630',
'https://www.raptorsupplies.de/pd/destaco/640',
'https://www.raptorsupplies.de/pd/destaco/602',
'https://www.raptorsupplies.de/pd/destaco/604',
'https://www.raptorsupplies.de/pd/destaco/624',
'https://www.raptorsupplies.de/pd/destaco/602-ss',
'https://www.raptorsupplies.de/pd/destaco/604-ss',
'https://www.raptorsupplies.de/pd/destaco/624-ss',
'https://www.raptorsupplies.de/pd/destaco/603-ss',
'https://www.raptorsupplies.de/pd/destaco/603-r',
'https://www.raptorsupplies.de/pd/destaco/630-r',
'https://www.raptorsupplies.de/pd/destaco/207206',
'https://www.raptorsupplies.de/pd/destaco/210206',
'https://www.raptorsupplies.de/pd/destaco/250206',
'https://www.raptorsupplies.de/pd/destaco/468206',
'https://www.raptorsupplies.de/pd/destaco/507206',
'https://www.raptorsupplies.de/pd/destaco/468206-m',
'https://www.raptorsupplies.de/pd/destaco/202',
'https://www.raptorsupplies.de/pd/destaco/2002-u',
'https://www.raptorsupplies.de/pd/destaco/2007-u',
'https://www.raptorsupplies.de/pd/destaco/2010-u',
'https://www.raptorsupplies.de/pd/destaco/2013-u',
'https://www.raptorsupplies.de/pd/destaco/2017-u',
'https://www.raptorsupplies.de/pd/destaco/201-u',
'https://www.raptorsupplies.de/pd/destaco/2027-u',
'https://www.raptorsupplies.de/pd/destaco/202-u',
'https://www.raptorsupplies.de/pd/destaco/207-s',
'https://www.raptorsupplies.de/pd/destaco/207-u',
'https://www.raptorsupplies.de/pd/destaco/207-ul',
'https://www.raptorsupplies.de/pd/destaco/210-s',
'https://www.raptorsupplies.de/pd/destaco/210-u',
'https://www.raptorsupplies.de/pd/destaco/247-u',
'https://www.raptorsupplies.de/pd/destaco/267-u',
'https://www.raptorsupplies.de/pd/destaco/201-uss',
'https://www.raptorsupplies.de/pd/destaco/202-uss',
'https://www.raptorsupplies.de/pd/destaco/207-uss',
'https://www.raptorsupplies.de/pd/destaco/210-uss',
'https://www.raptorsupplies.de/pd/destaco/2002-ur',
'https://www.raptorsupplies.de/pd/destaco/2007-ur',
'https://www.raptorsupplies.de/pd/destaco/2010-ur',
'https://www.raptorsupplies.de/pd/destaco/207-ur',
'https://www.raptorsupplies.de/pd/destaco/210-ur',
'https://www.raptorsupplies.de/pd/destaco/604106',
'https://www.raptorsupplies.de/pd/destaco/cpi-gpm-15-18',
'https://www.raptorsupplies.de/pd/destaco/810151',
'https://www.raptorsupplies.de/pd/destaco/810155',
'https://www.raptorsupplies.de/pd/destaco/810158',
'https://www.raptorsupplies.de/pd/destaco/202-tu',
'https://www.raptorsupplies.de/pd/destaco/858',
'https://www.raptorsupplies.de/pd/destaco/sts0013-na',
'https://www.raptorsupplies.de/pd/destaco/800',
'https://www.raptorsupplies.de/pd/destaco/870-2',
'https://www.raptorsupplies.de/pd/destaco/202-ub',
'https://www.raptorsupplies.de/pd/destaco/207-lb',
'https://www.raptorsupplies.de/pd/destaco/227-ub',
'https://www.raptorsupplies.de/pd/destaco/602-mm',
'https://www.raptorsupplies.de/pd/destaco/603-mr',
'https://www.raptorsupplies.de/pd/destaco/210209',
'https://www.raptorsupplies.de/pd/destaco/235208-m',
'https://www.raptorsupplies.de/pd/destaco/307208-m',
'https://www.raptorsupplies.de/pd/destaco/462',
'https://www.raptorsupplies.de/pd/destaco/462-2',
'https://www.raptorsupplies.de/pd/destaco/604-mm',
'https://www.raptorsupplies.de/pd/destaco/609-b',
'https://www.raptorsupplies.de/pd/destaco/202-ul',
'https://www.raptorsupplies.de/pd/destaco/802-u-rc',
'https://www.raptorsupplies.de/pd/destaco/841',
'https://www.raptorsupplies.de/pd/destaco/891',
'https://www.raptorsupplies.de/pd/destaco/6015-r',
'https://www.raptorsupplies.de/pd/destaco/6015',
'https://www.raptorsupplies.de/pd/destaco/5310-b',
'https://www.raptorsupplies.de/pd/destaco/202-b',
'https://www.raptorsupplies.de/pd/destaco/601-ss',
'https://www.raptorsupplies.de/pd/destaco/cpi-pat-75t-96',
'https://www.raptorsupplies.de/pd/destaco/dlm-07m-25-25-p',
'https://www.raptorsupplies.de/pd/destaco/rp-15',
'https://www.raptorsupplies.de/pd/destaco/rpl-2',
'https://www.raptorsupplies.de/pd/destaco/rpw-500-2',
'https://www.raptorsupplies.de/pd/destaco/rr-36-180',
'https://www.raptorsupplies.de/pd/destaco/rpl-4',
'https://www.raptorsupplies.de/pd/destaco/235-uss',
'https://www.raptorsupplies.de/pd/destaco/5130-mr',
'https://www.raptorsupplies.de/pd/destaco/5110-br',
'https://www.raptorsupplies.de/pd/destaco/5105-br',
'https://www.raptorsupplies.de/pd/destaco/385-l-m-25',
'https://www.raptorsupplies.de/pd/destaco/375-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/375-m-100',
'https://www.raptorsupplies.de/pd/destaco/375-b-m-50',
'https://www.raptorsupplies.de/pd/destaco/371-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/371-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/371-m-50',
'https://www.raptorsupplies.de/pd/destaco/351-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/351-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/344-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/341-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/341-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/334-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/330-m-25',
'https://www.raptorsupplies.de/pd/destaco/323-rss-m-50',
'https://www.raptorsupplies.de/pd/destaco/323-rss-m-100',
'https://www.raptorsupplies.de/pd/destaco/323-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/227-ub-l',
'https://www.raptorsupplies.de/pd/destaco/217-u-l',
'https://www.raptorsupplies.de/pd/destaco/217-ub',
'https://www.raptorsupplies.de/pd/destaco/207-ub-l',
'https://www.raptorsupplies.de/pd/destaco/2010-ubr',
'https://www.raptorsupplies.de/pd/destaco/2010-sr',
'https://www.raptorsupplies.de/pd/destaco/2007-sbr',
'https://www.raptorsupplies.de/pd/destaco/2002-sb',
'https://www.raptorsupplies.de/pd/destaco/2002-sr207',
'https://www.raptorsupplies.de/pd/destaco/2010-sb',
'https://www.raptorsupplies.de/pd/destaco/2010-sbr',
'https://www.raptorsupplies.de/pd/destaco/202-ub-l',
'https://www.raptorsupplies.de/pd/destaco/207-sb',
'https://www.raptorsupplies.de/pd/destaco/207-tu',
'https://www.raptorsupplies.de/pd/destaco/207-u-l',
'https://www.raptorsupplies.de/pd/destaco/213-u-l',
'https://www.raptorsupplies.de/pd/destaco/213-ub',
'https://www.raptorsupplies.de/pd/destaco/217-ub-l',
'https://www.raptorsupplies.de/pd/destaco/227-u-l',
'https://www.raptorsupplies.de/pd/destaco/323-m-100',
'https://www.raptorsupplies.de/pd/destaco/323-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/323-rss-m-25',
'https://www.raptorsupplies.de/pd/destaco/324-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/324-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/341-m-100',
'https://www.raptorsupplies.de/pd/destaco/344-m-25',
'https://www.raptorsupplies.de/pd/destaco/344-m-50',
'https://www.raptorsupplies.de/pd/destaco/344-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/344-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/351-b-m-50',
'https://www.raptorsupplies.de/pd/destaco/351-b-m-100',
'https://www.raptorsupplies.de/pd/destaco/351-b-m-25',
'https://www.raptorsupplies.de/pd/destaco/351-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/353-35',
'https://www.raptorsupplies.de/pd/destaco/371-m-25',
'https://www.raptorsupplies.de/pd/destaco/371-ss',
'https://www.raptorsupplies.de/pd/destaco/375-b-m-100',
'https://www.raptorsupplies.de/pd/destaco/374-m-50',
'https://www.raptorsupplies.de/pd/destaco/375-b-m-25',
'https://www.raptorsupplies.de/pd/destaco/503-mblsc',
'https://www.raptorsupplies.de/pd/destaco/506-mlblsc',
'https://www.raptorsupplies.de/pd/destaco/5105-b',
'https://www.raptorsupplies.de/pd/destaco/5110-b',
'https://www.raptorsupplies.de/pd/destaco/5110-r',
'https://www.raptorsupplies.de/pd/destaco/5130-br',
'https://www.raptorsupplies.de/pd/destaco/5130-mbr',
'https://www.raptorsupplies.de/pd/destaco/5130-r',
'https://www.raptorsupplies.de/pd/destaco/5131-br',
'https://www.raptorsupplies.de/pd/destaco/5131-mb',
'https://www.raptorsupplies.de/pd/destaco/5131-mr',
'https://www.raptorsupplies.de/pd/destaco/5133-mr',
'https://www.raptorsupplies.de/pd/destaco/5133-mbr',
'https://www.raptorsupplies.de/pd/destaco/5133-mb',
'https://www.raptorsupplies.de/pd/destaco/5150-r',
'https://www.raptorsupplies.de/pd/destaco/5150-mb',
'https://www.raptorsupplies.de/pd/destaco/5150-mbr',
'https://www.raptorsupplies.de/pd/destaco/5150-mr',
'https://www.raptorsupplies.de/pd/destaco/6001-ss',
'https://www.raptorsupplies.de/pd/destaco/6015-ss',
'https://www.raptorsupplies.de/pd/destaco/602-mmss',
'https://www.raptorsupplies.de/pd/destaco/607-sqm',
'https://www.raptorsupplies.de/pd/destaco/690-1mbpls',
'https://www.raptorsupplies.de/pd/destaco/803-me',
'https://www.raptorsupplies.de/pd/destaco/803-rc',
'https://www.raptorsupplies.de/pd/destaco/807-se',
'https://www.raptorsupplies.de/pd/destaco/810-ue',
'https://www.raptorsupplies.de/pd/destaco/817-u-lc',
'https://www.raptorsupplies.de/pd/destaco/827-s-lc',
'https://www.raptorsupplies.de/pd/destaco/82l4n-26300h0b',
'https://www.raptorsupplies.de/pd/destaco/830-me',
'https://www.raptorsupplies.de/pd/destaco/847-s-lc',
'https://www.raptorsupplies.de/pd/destaco/850-me',
'https://www.raptorsupplies.de/pd/destaco/858-e',
'https://www.raptorsupplies.de/pd/destaco/868-e',
'https://www.raptorsupplies.de/pd/destaco/fo-220',
'https://www.raptorsupplies.de/pd/destaco/5305',
'https://www.raptorsupplies.de/pd/destaco/695-1mbpls',
'https://www.raptorsupplies.de/pd/destaco/506-mblsc',
'https://www.raptorsupplies.de/pd/destaco/323-rss',
'https://www.raptorsupplies.de/pd/destaco/5131-b',
'https://www.raptorsupplies.de/pd/destaco/604-mmss',
'https://www.raptorsupplies.de/pd/destaco/323-m-25',
'https://www.raptorsupplies.de/pd/destaco/2002-s207',
'https://www.raptorsupplies.de/pd/destaco/5310',
'https://www.raptorsupplies.de/pd/destaco/5305-b',
'https://www.raptorsupplies.de/pd/destaco/5150-m',
'https://www.raptorsupplies.de/pd/destaco/807-u-rc',
'https://www.raptorsupplies.de/pd/destaco/6004-mm',
'https://www.raptorsupplies.de/pd/destaco/614-m',
'https://www.raptorsupplies.de/pd/destaco/341-m-25',
'https://www.raptorsupplies.de/pd/destaco/323-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/225-ubss',
'https://www.raptorsupplies.de/pd/destaco/812-u-rc',
'https://www.raptorsupplies.de/pd/destaco/817-s-lc',
'https://www.raptorsupplies.de/pd/destaco/2002-ubr',
'https://www.raptorsupplies.de/pd/destaco/324-m-25',
'https://www.raptorsupplies.de/pd/destaco/207-lbr',
'https://www.raptorsupplies.de/pd/destaco/2002-sr',
'https://www.raptorsupplies.de/pd/destaco/324-m-50',
'https://www.raptorsupplies.de/pd/destaco/807-ue',
'https://www.raptorsupplies.de/pd/destaco/807-s-rc',
'https://www.raptorsupplies.de/pd/destaco/8007-e',
'https://www.raptorsupplies.de/pd/destaco/8007-ehl',
'https://www.raptorsupplies.de/pd/destaco/385-l-m-100',
'https://www.raptorsupplies.de/pd/destaco/fo-162-60',
'https://www.raptorsupplies.de/pd/destaco/2002-u207',
'https://www.raptorsupplies.de/pd/destaco/3011',
'https://www.raptorsupplies.de/pd/destaco/802-u-lc',
'https://www.raptorsupplies.de/pd/destaco/630-mr',
'https://www.raptorsupplies.de/pd/destaco/810-s-rc',
'https://www.raptorsupplies.de/pd/destaco/fo-221-80',
'https://www.raptorsupplies.de/pd/destaco/5131-r',
'https://www.raptorsupplies.de/pd/destaco/535-lb',
'https://www.raptorsupplies.de/pd/destaco/351-m-25',
'https://www.raptorsupplies.de/pd/destaco/5310-r',
'https://www.raptorsupplies.de/pd/destaco/5310-br',
'https://www.raptorsupplies.de/pd/destaco/5905-b',
'https://www.raptorsupplies.de/pd/destaco/324-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/fl-162-60',
'https://www.raptorsupplies.de/pd/destaco/g-120',
'https://www.raptorsupplies.de/pd/destaco/6004',
'https://www.raptorsupplies.de/pd/destaco/5915',
'https://www.raptorsupplies.de/pd/destaco/5131-m',
'https://www.raptorsupplies.de/pd/destaco/375-m-50',
'https://www.raptorsupplies.de/pd/destaco/8007-ehr',
'https://www.raptorsupplies.de/pd/destaco/334-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/846',
'https://www.raptorsupplies.de/pd/destaco/827-s',
'https://www.raptorsupplies.de/pd/destaco/205-sb',
'https://www.raptorsupplies.de/pd/destaco/205-ub',
'https://www.raptorsupplies.de/pd/destaco/206-hss',
'https://www.raptorsupplies.de/pd/destaco/601-o',
'https://www.raptorsupplies.de/pd/destaco/615',
'https://www.raptorsupplies.de/pd/destaco/620',
'https://www.raptorsupplies.de/pd/destaco/f-160',
'https://www.raptorsupplies.de/pd/destaco/fl-120',
'https://www.raptorsupplies.de/pd/destaco/fl-121-45',
'https://www.raptorsupplies.de/pd/destaco/fl-160',
'https://www.raptorsupplies.de/pd/destaco/fl-161-60',
'https://www.raptorsupplies.de/pd/destaco/fo-082-40',
'https://www.raptorsupplies.de/pd/destaco/fo-120',
'https://www.raptorsupplies.de/pd/destaco/fo-121-45',
'https://www.raptorsupplies.de/pd/destaco/fo-122-45',
'https://www.raptorsupplies.de/pd/destaco/fo-160',
'https://www.raptorsupplies.de/pd/destaco/fo-161-60',
'https://www.raptorsupplies.de/pd/destaco/g-082-40',
'https://www.raptorsupplies.de/pd/destaco/g-121-45',
'https://www.raptorsupplies.de/pd/destaco/210-tu',
'https://www.raptorsupplies.de/pd/destaco/210-ub',
'https://www.raptorsupplies.de/pd/destaco/351-m-50',
'https://www.raptorsupplies.de/pd/destaco/351-m-100',
'https://www.raptorsupplies.de/pd/destaco/503-mlblsc',
'https://www.raptorsupplies.de/pd/destaco/505-mlblsc',
'https://www.raptorsupplies.de/pd/destaco/505-mblsc',
'https://www.raptorsupplies.de/pd/destaco/247-ub',
'https://www.raptorsupplies.de/pd/destaco/381-ss',
'https://www.raptorsupplies.de/pd/destaco/374-m-25',
'https://www.raptorsupplies.de/pd/destaco/g-122-45',
'https://www.raptorsupplies.de/pd/destaco/317-s',
'https://www.raptorsupplies.de/pd/destaco/527',
'https://www.raptorsupplies.de/pd/destaco/847-u-rc',
'https://www.raptorsupplies.de/pd/destaco/385-v2a',
'https://www.raptorsupplies.de/pd/destaco/601-m',
'https://www.raptorsupplies.de/pd/destaco/624-mm',
'https://www.raptorsupplies.de/pd/destaco/603-m',
'https://www.raptorsupplies.de/pd/destaco/605-m',
'https://www.raptorsupplies.de/pd/destaco/607-m',
'https://www.raptorsupplies.de/pd/destaco/610-m',
'https://www.raptorsupplies.de/pd/destaco/620-m',
'https://www.raptorsupplies.de/pd/destaco/630-m',
'https://www.raptorsupplies.de/pd/destaco/640-m',
'https://www.raptorsupplies.de/pd/destaco/650-m',
'https://www.raptorsupplies.de/pd/destaco/7-101',
'https://www.raptorsupplies.de/pd/destaco/7-58',
'https://www.raptorsupplies.de/pd/destaco/7-59',
'https://www.raptorsupplies.de/pd/destaco/7-60',
'https://www.raptorsupplies.de/pd/destaco/807-s-lc',
'https://www.raptorsupplies.de/pd/destaco/331-m-100',
'https://www.raptorsupplies.de/pd/destaco/812-u-lc',
'https://www.raptorsupplies.de/pd/destaco/2002-ur207',
'https://www.raptorsupplies.de/pd/destaco/505-mb',
'https://www.raptorsupplies.de/pd/destaco/341-m-50',
'https://www.raptorsupplies.de/pd/destaco/301-ss',
'https://www.raptorsupplies.de/pd/destaco/351-bss',
'https://www.raptorsupplies.de/pd/destaco/375-b',
'https://www.raptorsupplies.de/pd/destaco/601-oss',
'https://www.raptorsupplies.de/pd/destaco/607-sq',
'https://www.raptorsupplies.de/pd/destaco/890',
'https://www.raptorsupplies.de/pd/destaco/201-ub',
'https://www.raptorsupplies.de/pd/destaco/578',
'https://www.raptorsupplies.de/pd/destaco/374',
'https://www.raptorsupplies.de/pd/destaco/431',
'https://www.raptorsupplies.de/pd/destaco/486',
'https://www.raptorsupplies.de/pd/destaco/371-r',
'https://www.raptorsupplies.de/pd/destaco/91090',
'https://www.raptorsupplies.de/pd/destaco/95030',
'https://www.raptorsupplies.de/pd/destaco/95040',
'https://www.raptorsupplies.de/pd/destaco/95050',
'https://www.raptorsupplies.de/pd/destaco/95060',
'https://www.raptorsupplies.de/pd/destaco/830-rc',
'https://www.raptorsupplies.de/pd/destaco/345-g',
'https://www.raptorsupplies.de/pd/destaco/2002-s',
'https://www.raptorsupplies.de/pd/destaco/2002-ub',
'https://www.raptorsupplies.de/pd/destaco/2007-s',
'https://www.raptorsupplies.de/pd/destaco/2007-ub',
'https://www.raptorsupplies.de/pd/destaco/2010-s',
'https://www.raptorsupplies.de/pd/destaco/2010-ub',
'https://www.raptorsupplies.de/pd/destaco/381-m-25',
'https://www.raptorsupplies.de/pd/destaco/606',
'https://www.raptorsupplies.de/pd/destaco/351-b',
'https://www.raptorsupplies.de/pd/destaco/207-ub',
'https://www.raptorsupplies.de/pd/destaco/334-m-25',
'https://www.raptorsupplies.de/pd/destaco/207-sf',
'https://www.raptorsupplies.de/pd/destaco/381-m-50',
'https://www.raptorsupplies.de/pd/destaco/207-lr',
'https://www.raptorsupplies.de/pd/destaco/210-sr',
'https://www.raptorsupplies.de/pd/destaco/351-r',
'https://www.raptorsupplies.de/pd/destaco/807-u-ht',
'https://www.raptorsupplies.de/pd/destaco/330-m-50',
'https://www.raptorsupplies.de/pd/destaco/330-m-100',
'https://www.raptorsupplies.de/pd/destaco/810-u-rc',
'https://www.raptorsupplies.de/pd/destaco/331-m-25',
'https://www.raptorsupplies.de/pd/destaco/5105-r',
'https://www.raptorsupplies.de/pd/destaco/344-m-100',
'https://www.raptorsupplies.de/pd/destaco/334-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/817-se',
'https://www.raptorsupplies.de/pd/destaco/323-m-50',
'https://www.raptorsupplies.de/pd/destaco/2007-sr',
'https://www.raptorsupplies.de/pd/destaco/2007-ubr',
'https://www.raptorsupplies.de/pd/destaco/5910-b',
'https://www.raptorsupplies.de/pd/destaco/5133-b',
'https://www.raptorsupplies.de/pd/destaco/5150-b',
'https://www.raptorsupplies.de/pd/destaco/2007-sb',
'https://www.raptorsupplies.de/pd/destaco/331-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/802-ue',
'https://www.raptorsupplies.de/pd/destaco/213-ub-l',
'https://www.raptorsupplies.de/pd/destaco/5133-r',
'https://www.raptorsupplies.de/pd/destaco/6001',
'https://www.raptorsupplies.de/pd/destaco/817-ue',
'https://www.raptorsupplies.de/pd/destaco/5130-m',
'https://www.raptorsupplies.de/pd/destaco/5910',
'https://www.raptorsupplies.de/pd/destaco/5150',
'https://www.raptorsupplies.de/pd/destaco/3051',
'https://www.raptorsupplies.de/pd/destaco/5130',
'https://www.raptorsupplies.de/pd/destaco/5105',
'https://www.raptorsupplies.de/pd/destaco/5131',
'https://www.raptorsupplies.de/pd/destaco/5133',
'https://www.raptorsupplies.de/pd/destaco/fl-122-45',
'https://www.raptorsupplies.de/pd/destaco/868-lc',
'https://www.raptorsupplies.de/pd/destaco/847-u-lc',
'https://www.raptorsupplies.de/pd/destaco/827-ue',
'https://www.raptorsupplies.de/pd/destaco/827-se',
'https://www.raptorsupplies.de/pd/destaco/810-u-lc',
'https://www.raptorsupplies.de/pd/destaco/810-se',
'https://www.raptorsupplies.de/pd/destaco/807-u-lc',
'https://www.raptorsupplies.de/pd/destaco/807-s-ht',
'https://www.raptorsupplies.de/pd/destaco/8021-ue',
'https://www.raptorsupplies.de/pd/destaco/640-r',
'https://www.raptorsupplies.de/pd/destaco/8071-ue',
'https://www.raptorsupplies.de/pd/destaco/533-lb',
'https://www.raptorsupplies.de/pd/destaco/5305-r',
'https://www.raptorsupplies.de/pd/destaco/5131-mbr',
'https://www.raptorsupplies.de/pd/destaco/5150-br',
'https://www.raptorsupplies.de/pd/destaco/5133-br',
'https://www.raptorsupplies.de/pd/destaco/5130-mb',
'https://www.raptorsupplies.de/pd/destaco/528',
'https://www.raptorsupplies.de/pd/destaco/424-2',
'https://www.raptorsupplies.de/pd/destaco/205-ul',
'https://www.raptorsupplies.de/pd/destaco/235-ub',
'https://www.raptorsupplies.de/pd/destaco/528-f',
'https://www.raptorsupplies.de/pd/destaco/205-sl',
'https://www.raptorsupplies.de/pd/destaco/205-sr',
'https://www.raptorsupplies.de/pd/destaco/207-ulb',
'https://www.raptorsupplies.de/pd/destaco/861',
'https://www.raptorsupplies.de/pd/destaco/225-ub',
'https://www.raptorsupplies.de/pd/destaco/385-l',
'https://www.raptorsupplies.de/pd/destaco/375-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/334-r',
'https://www.raptorsupplies.de/pd/destaco/202-u-l',
'https://www.raptorsupplies.de/pd/destaco/548',
'https://www.raptorsupplies.de/pd/destaco/3051-r',
'https://www.raptorsupplies.de/pd/destaco/344-r',
'https://www.raptorsupplies.de/pd/destaco/847-s-rc',
'https://www.raptorsupplies.de/pd/destaco/331-m-50',
'https://www.raptorsupplies.de/pd/destaco/608-m',
'https://www.raptorsupplies.de/pd/destaco/385-m-25',
'https://www.raptorsupplies.de/pd/destaco/501-b',
'https://www.raptorsupplies.de/pd/destaco/505-mlb',
'https://www.raptorsupplies.de/pd/destaco/501-lb',
'https://www.raptorsupplies.de/pd/destaco/207-uf',
'https://www.raptorsupplies.de/pd/destaco/375-m-25',
'https://www.raptorsupplies.de/pd/destaco/267-s',
'https://www.raptorsupplies.de/pd/destaco/385-m-50',
'https://www.raptorsupplies.de/pd/destaco/201-tu',
'https://www.raptorsupplies.de/pd/destaco/202-ss',
'https://www.raptorsupplies.de/pd/destaco/202-t',
'https://www.raptorsupplies.de/pd/destaco/215-s',
'https://www.raptorsupplies.de/pd/destaco/229',
'https://www.raptorsupplies.de/pd/destaco/247-s',
'https://www.raptorsupplies.de/pd/destaco/245-u',
'https://www.raptorsupplies.de/pd/destaco/374-m-100',
'https://www.raptorsupplies.de/pd/destaco/334-m-100',
'https://www.raptorsupplies.de/pd/destaco/371-m-100',
'https://www.raptorsupplies.de/pd/destaco/385-m-100',
'https://www.raptorsupplies.de/pd/destaco/503-mlb',
'https://www.raptorsupplies.de/pd/destaco/331-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/5133-m',
'https://www.raptorsupplies.de/pd/destaco/5130-b',
'https://www.raptorsupplies.de/pd/destaco/5305-br',
'https://www.raptorsupplies.de/pd/destaco/381-m-100',
'https://www.raptorsupplies.de/pd/destaco/385-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/324-r',
'https://www.raptorsupplies.de/pd/destaco/830-lc',
'https://www.raptorsupplies.de/pd/destaco/810-s-lc',
'https://www.raptorsupplies.de/pd/destaco/207-tul',
'https://www.raptorsupplies.de/pd/destaco/506-mb',
'https://www.raptorsupplies.de/pd/destaco/375-br',
'https://www.raptorsupplies.de/pd/destaco/353-65',
'https://www.raptorsupplies.de/pd/destaco/341-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/533-l',
'https://www.raptorsupplies.de/pd/destaco/535-l',
'https://www.raptorsupplies.de/pd/destaco/385-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/385-l-m-50',
'https://www.raptorsupplies.de/pd/destaco/324-m-100',
'https://www.raptorsupplies.de/pd/destaco/675-1mbpls',
'https://www.raptorsupplies.de/pd/destaco/425',
'https://www.raptorsupplies.de/pd/destaco/435',
'https://www.raptorsupplies.de/pd/destaco/6001-m',
'https://www.raptorsupplies.de/pd/destaco/6001-mss',
'https://www.raptorsupplies.de/pd/destaco/6015-mr',
'https://www.raptorsupplies.de/pd/destaco/6015-mss',
'https://www.raptorsupplies.de/pd/destaco/807-s',
'https://www.raptorsupplies.de/pd/destaco/810-s',
'https://www.raptorsupplies.de/pd/destaco/817-s',
'https://www.raptorsupplies.de/pd/destaco/817-u',
'https://www.raptorsupplies.de/pd/destaco/827-u',
'https://www.raptorsupplies.de/pd/destaco/847-s',
'https://www.raptorsupplies.de/pd/destaco/847-u',
'https://www.raptorsupplies.de/pd/destaco/850',
'https://www.raptorsupplies.de/pd/destaco/868',
'https://www.raptorsupplies.de/pd/destaco/506-mlb',
'https://www.raptorsupplies.de/pd/destaco/640-mr',
'https://www.raptorsupplies.de/pd/destaco/323-r',
'https://www.raptorsupplies.de/pd/destaco/858-lc',
'https://www.raptorsupplies.de/pd/destaco/860',
'https://www.raptorsupplies.de/pd/destaco/237-uss',
'https://www.raptorsupplies.de/pd/destaco/331-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/2002-sbr',
'https://www.raptorsupplies.de/pd/destaco/375-r-m-25',
'https://www.raptorsupplies.de/pd/destaco/385-r-m-50',
'https://www.raptorsupplies.de/pd/destaco/5110',
'https://www.raptorsupplies.de/pd/destaco/5905',
'https://www.raptorsupplies.de/pd/destaco/670-1mbpls',
'https://www.raptorsupplies.de/pd/destaco/371-r-m-100',
'https://www.raptorsupplies.de/pd/destaco/827-u-lc',
'https://www.raptorsupplies.de/pd/destaco/603-mss',
'https://www.raptorsupplies.de/pd/destaco/334-m-50',
'https://www.raptorsupplies.de/pd/destaco/803-lc',
'https://www.raptorsupplies.de/pd/destaco/215-ub',
'https://www.raptorsupplies.de/pd/destaco/345',
'https://www.raptorsupplies.de/pd/destaco/205-ur',
'https://www.raptorsupplies.de/pd/destaco/840',
'https://www.raptorsupplies.de/pd/destaco/201208-m',
'https://www.raptorsupplies.de/pd/destaco/205208-m'
]
     for x in range(0,605):
         print(x)
         print(list[x])
         get_details(list[x])

