import requests
from bs4 import BeautifulSoup
from typing import TextIO
import re

myresult=['https://eberbachlabtools.com/products/trichome-separation-collection-system',
'https://eberbachlabtools.com/products/shaker-bath',
'https://eberbachlabtools.com/products/e1000-electro-analyzer',
'https://eberbachlabtools.com/products/cathetometer',
'https://eberbachlabtools.com/products/hot-wire-glass-tube-cutter-kit',
'https://eberbachlabtools.com/products/mobile-lift-assist',
'https://eberbachlabtools.com/products/electro-analyzer-sample-heater',
'https://eberbachlabtools.com/products/electrode-adaptor-stainless-steel',
'https://eberbachlabtools.com/products/glass-agitator',
'https://eberbachlabtools.com/products/foot-pedal-unit',
'https://eberbachlabtools.com/products/telescope',
'https://eberbachlabtools.com/products/cathetometer-imaging-system',
'https://eberbachlabtools.com/products/cathetometer-lighting-kit',
'https://eberbachlabtools.com/products/hot-wire-glass-tube-cutter',
'https://eberbachlabtools.com/products/cutting-wire-12ft',
'https://eberbachlabtools.com/products/cutting-wire-100ft',
'https://eberbachlabtools.com/products/e8400-safety-shield',
'https://eberbachlabtools.com/products/e8445-glass-container',
'https://eberbachlabtools.com/products/e8670-standard-blending-assembly',
'https://eberbachlabtools.com/products/e8447-glass-container',
'https://eberbachlabtools.com/products/e8452-2-piece-vinyl-lid',
'https://eberbachlabtools.com/products/e8506-2-piece-vinyl-lid',
'https://eberbachlabtools.com/products/e8511-stainless-steel-press-fit-lid',
'https://eberbachlabtools.com/products/e8620-cooling-coil',
'https://eberbachlabtools.com/products/e8671-sealed-blending-assembly',
'https://eberbachlabtools.com/products/e8672-stainless-steel-blending-assembly',
'https://eberbachlabtools.com/products/e8685-stainless-steel-pulverizing-blending-assembly',
'https://eberbachlabtools.com/products/e8690-stainless-steel-multi-blade-blending-assembly',
'https://eberbachlabtools.com/products/e8480-metal-screw-top-lid',
'https://eberbachlabtools.com/products/e8482-polypropylene-screw-top-lid',
'https://eberbachlabtools.com/products/e8483-o-ring-seal',
'https://eberbachlabtools.com/products/e8475-glass-container',
'https://eberbachlabtools.com/products/e8710-small-blending-assembly',
'https://eberbachlabtools.com/products/e8730-semi-micro-blending-assembly',
'https://eberbachlabtools.com/products/e8650-centrifugal-flow-blending-assembly',
'https://eberbachlabtools.com/products/e8731-sealed-semi-micro-blending-assembly',
'https://eberbachlabtools.com/products/e8732-stainless-steel-semi-micro-blending-assembly',
'https://eberbachlabtools.com/products/e8030-waring-4-liter-blending-container-lid',
'https://eberbachlabtools.com/products/e8035-waring-4-liter-blending-container-cover',
'https://eberbachlabtools.com/products/4l-blending-assembly',
'https://eberbachlabtools.com/products/wrench-set',
'https://eberbachlabtools.com/products/e8051-1l-blending-container-adapter',
'https://eberbachlabtools.com/products/small-size-blending-blades',
'https://eberbachlabtools.com/products/press-fit-lid',
'https://eberbachlabtools.com/products/1-liter-variable-speed-blender',
'https://eberbachlabtools.com/products/waring%C2%AE-4-liter-coupling-assembly',
'https://eberbachlabtools.com/products/harsh-condition-assembly',
'https://eberbachlabtools.com/products/blade-assembly',
'https://eberbachlabtools.com/products/blade-assembly-1',
'https://eberbachlabtools.com/products/stainless-steel-small-size-blending-assembly',
'https://eberbachlabtools.com/products/blade-assembly-2',
'https://eberbachlabtools.com/products/sealed-blending-assembly',
'https://eberbachlabtools.com/products/coupling-assembly',
'https://eberbachlabtools.com/products/waring-4-liter-blending-container-lid',
'https://eberbachlabtools.com/products/waring-4-liter-cool-base-container',
'https://eberbachlabtools.com/products/waring-1-2-liter-glass-blending-container',
'https://eberbachlabtools.com/products/waring-1-liter-stainless-steel-blending-container',
'https://eberbachlabtools.com/products/waring-1-liter-stainless-steel-blending-container-press-fit-lid',
'https://eberbachlabtools.com/products/heavy-duty-1-liter-blending-container',
'https://eberbachlabtools.com/products/1-liter-heavy-duty-stainless-steel-blending-container',
'https://eberbachlabtools.com/products/heavy-duty-1-liter-stainless-steel-blending-container',
'https://eberbachlabtools.com/products/heavy-duty-1-liter-pulverizing-blending-container',
'https://eberbachlabtools.com/products/heavy-duty-1-liter-multi-blade-blending-container',
'https://eberbachlabtools.com/products/500ml-borosilicate-glass-blending-container',
'https://eberbachlabtools.com/products/150-ml-polypropylene-blending-container',
'https://eberbachlabtools.com/products/500-ml-graduated-cylinder-blending-container',
'https://eberbachlabtools.com/products/250-ml-borosilicate-glass-blending-container',
'https://eberbachlabtools.com/products/250-ml-centrifugal-flow-blending-container',
'https://eberbachlabtools.com/products/stainless-steel-micro-blending-container',
'https://eberbachlabtools.com/products/250-ml-blending-container-with-cooling-jacket',
'https://eberbachlabtools.com/products/360-ml-stainless-steel-semi-micro-blending-container',
'https://eberbachlabtools.com/products/360-ml-stainless-steel-semi-micro-blending-container-with-screw-top-lid',
'https://eberbachlabtools.com/products/360-ml-stainless-steel-sealed-semi-micro-blending-container-with-screw-top-lid-with-sealed-blending-assembly',
'https://eberbachlabtools.com/products/360-ml-all-stainless-steel-semi-micro-blending-container',
'https://eberbachlabtools.com/products/semi-micro-cooling-blending-container',
'https://eberbachlabtools.com/products/waring-37-ml-mini-blending-container',
'https://eberbachlabtools.com/products/waring-110-ml-mini-blending-container',
'https://eberbachlabtools.com/products/waring-250-ml-mini-blending-container',
'https://eberbachlabtools.com/products/borosilicate-glass-jar-heat-resistant-without-hole',
'https://eberbachlabtools.com/products/6-cup-glass-container-with-lid',
'https://eberbachlabtools.com/products/variable-speed-mini-cutting-mill',
'https://eberbachlabtools.com/products/cgmp-suitable-variable-speed-cutting-mill-with-vacuum-collection-system',
'https://eberbachlabtools.com/products/single-speed-mini-cutting-mill',
'https://eberbachlabtools.com/products/single-speed-cutting-mill',
'https://eberbachlabtools.com/products/variable-speed-cutting-mill',
'https://eberbachlabtools.com/products/heavy-duty-single-speed-cutting-mill',
'https://eberbachlabtools.com/products/heavy-duty-variable-speed-cutting-mills',
'https://eberbachlabtools.com/products/high-throughput-variable-speed-cutting-mill',
'https://eberbachlabtools.com/products/food-grade-variable-speed-heavy-duty-cutting-mills',
'https://eberbachlabtools.com/products/stainless-steel-variable-speed-cutting-mill',
'https://eberbachlabtools.com/products/copy-of-heavy-duty-variable-speed-cutting-mill',
'https://eberbachlabtools.com/products/high-speed-explosion-proof-overhead-stirrer',
'https://eberbachlabtools.com/products/high-torque-explosion-proof-overhead-stirrer',
'https://eberbachlabtools.com/products/foot-pedal',
'https://eberbachlabtools.com/products/high-powered-single-speed-blender',
'https://eberbachlabtools.com/products/high-powered-digital-variable-speed-blender',
'https://eberbachlabtools.com/products/high-powered-single-speed-explosion-resistant-blender',
'https://eberbachlabtools.com/products/high-powered-variable-speed-explosion-resistant-blender',
'https://eberbachlabtools.com/products/1-liter-two-speed-blender-with-timer',
'https://eberbachlabtools.com/products/overhead-stirrer',
'https://eberbachlabtools.com/products/power-stir%C2%AE',
'https://eberbachlabtools.com/products/high-temp-incubator-oven',
'https://eberbachlabtools.com/products/programmable-inversion-tumbler',
'https://eberbachlabtools.com/products/incubator-tumbler',
'https://eberbachlabtools.com/products/high-capacity-programmable-inversion-tumbler',
'https://eberbachlabtools.com/products/hand-motion-shaker',
'https://eberbachlabtools.com/products/heavy-duty-programmable-inversion-tumbler',
'https://eberbachlabtools.com/products/quechers-hand-motion-shaker',
'https://eberbachlabtools.com/products/explosion-proof-v-blender',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-blades',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-blades-e3700',
'https://eberbachlabtools.com/products/high-capacity-orbital-shaker',
'https://eberbachlabtools.com/products/thawing-enclosure',
'https://eberbachlabtools.com/products/stainless-steel-large-batch-blender',
'https://eberbachlabtools.com/products/20-liter-explosion-proof-blender',
'https://eberbachlabtools.com/products/e3300-a-s10-s60-mesh-sieves',
'https://eberbachlabtools.com/products/e3300-mesh-sieves-80-100',
'https://eberbachlabtools.com/products/e3300-rotating-cutter-head',
'https://eberbachlabtools.com/products/e3300-stationary-blade-set',
'https://eberbachlabtools.com/products/e3500-mill-stand',
'https://eberbachlabtools.com/products/e3500-sieves',
'https://eberbachlabtools.com/products/e3500-rotating-blade-set',
'https://eberbachlabtools.com/products/e3500-stationary-blade-set',
'https://eberbachlabtools.com/products/e3200-mill-enclosure-with-exhaust-fan',
'https://eberbachlabtools.com/products/e3700-mill-stand',
'https://eberbachlabtools.com/products/e3700-high-flow-hopper',
'https://eberbachlabtools.com/products/e3700-mill-plunger',
'https://eberbachlabtools.com/products/e3700-sieves',
'https://eberbachlabtools.com/products/e3700-rotating-cutter-head-6-edges',
'https://eberbachlabtools.com/products/e3700-blade-gapping-tool',
'https://eberbachlabtools.com/products/e3700-rotating-blade-set',
'https://eberbachlabtools.com/products/e3700-stationary-blade-set',
'https://eberbachlabtools.com/products/e3800-sieves',
'https://eberbachlabtools.com/products/e3800-rotating-cutter-head',
'https://eberbachlabtools.com/products/e3800-rotating-cutter-head-1',
'https://eberbachlabtools.com/products/e3800-rotating-blade-set',
'https://eberbachlabtools.com/products/e3800-stationary-blade-set',
'https://eberbachlabtools.com/products/straight-4oz-collection-jar-with-lid',
'https://eberbachlabtools.com/products/3300-mill-plunger',
'https://eberbachlabtools.com/products/e3500-mill-plunger',
'https://eberbachlabtools.com/products/e3700-jar-holder',
'https://eberbachlabtools.com/products/e3700-loading-tray',
'https://eberbachlabtools.com/products/e3700-maintenance-tool-kit',
'https://eberbachlabtools.com/products/e3700-cleaning-kit',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-cutter-head-e3300',
'https://eberbachlabtools.com/products/vanax-superclean-stationary-cutter-head-e3300',
'https://eberbachlabtools.com/products/vanax-superclean-stationary-blades-e3500',
'https://eberbachlabtools.com/products/vanax-superclean-stationary-blade-set',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-blades-e3800',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-blades-set-of-6',
'https://eberbachlabtools.com/products/vanax-superclean-stationary-blade-set-1',
'https://eberbachlabtools.com/products/clinical-rotator',
'https://eberbachlabtools.com/products/e6130-benchtop-orbital-shaker',
'https://eberbachlabtools.com/products/medium-duty-orbital-shaker',
'https://eberbachlabtools.com/products/large-orbital-shaker',
'https://eberbachlabtools.com/products/heavy-duty-orbital-shaker-1',
'https://eberbachlabtools.com/products/fixed-speed-reciprocal-shaker',
'https://eberbachlabtools.com/products/digital-benchtop-reciprocal-shaker',
'https://eberbachlabtools.com/products/benchtop-reciprocal-shaker',
'https://eberbachlabtools.com/products/heavy-duty-reciprocal-shaker',
'https://eberbachlabtools.com/products/heavy-duty-reciprocating-shaker',
'https://eberbachlabtools.com/products/heavy-duty-digital-reciprocal-shaker',
'https://eberbachlabtools.com/products/production-duty-reciprocating-shaker',
'https://eberbachlabtools.com/products/explosion-proof-reciprocal-shaker',
'https://eberbachlabtools.com/products/medium-duty-reciprocal-shaker',
'https://eberbachlabtools.com/products/digital-medium-duty-reciprocal-shaker',
'https://eberbachlabtools.com/products/explosion-proof-medium-duty-reciprocal-shaker',
'https://eberbachlabtools.com/products/digital-variable-speed-reciprocal-shaker',
'https://eberbachlabtools.com/products/benchtop-hotplate-shaker',
'https://eberbachlabtools.com/products/ice-water-extractor',
'https://eberbachlabtools.com/products/e5713-reciprocal-shaker',
'https://eberbachlabtools.com/products/high-capacity-incubator-shaking-system',
'https://eberbachlabtools.com/products/long-stroke-reciprocating-shaker',
'https://eberbachlabtools.com/products/box-carrier',
'https://eberbachlabtools.com/products/shaker-stand',
'https://eberbachlabtools.com/products/bar-clamp',
'https://eberbachlabtools.com/products/box-carrier-with-plexiglass-cover',
'https://eberbachlabtools.com/products/dual-box-carrier-adapter',
'https://eberbachlabtools.com/products/shaker-platform',
'https://eberbachlabtools.com/products/erlenmeyer-flask-holder',
'https://eberbachlabtools.com/products/hard-case-with-spare-parts',
'https://eberbachlabtools.com/products/e5700-shaker-stand',
'https://eberbachlabtools.com/products/e5900-heavy-duty-stand',
'https://eberbachlabtools.com/products/e5910-platform',
'https://eberbachlabtools.com/products/e5913-easy-change-strips',
'https://eberbachlabtools.com/products/e5915-utility-box-conversion-kit',
'https://eberbachlabtools.com/products/e5917-crosswise-bar-clamp',
'https://eberbachlabtools.com/products/e5919-utility-box-carrier',
'https://eberbachlabtools.com/products/e6190-14-shaker-tiering-posts',
'https://eberbachlabtools.com/products/e5902-heavy-duty-stand',
'https://eberbachlabtools.com/products/e5919-rubber-mat',
'https://eberbachlabtools.com/products/e6000-heavy-duty-stand',
'https://eberbachlabtools.com/products/e2550-slide-carrier',
'https://eberbachlabtools.com/products/e2560-slide-carrier',
'https://eberbachlabtools.com/products/e2565-rotator-cover',
'https://eberbachlabtools.com/products/e6130-large-shaker-platform',
'https://eberbachlabtools.com/products/e6130-small-shaker-platform',
'https://eberbachlabtools.com/products/e6130-utility-box-carrier',
'https://eberbachlabtools.com/products/e6130-large-utility-box-carrier',
'https://eberbachlabtools.com/products/e6130-bar-clamp',
'https://eberbachlabtools.com/products/e6140-top-plate',
'https://eberbachlabtools.com/products/e6140-perforated-platform',
'https://eberbachlabtools.com/products/e6140-utility-box-carrier',
'https://eberbachlabtools.com/products/e6145-shaker-floor-stand',
'https://eberbachlabtools.com/products/e6162-utility-box-carrier-conversion-kit',
'https://eberbachlabtools.com/products/e6145-shaker-platform',
'https://eberbachlabtools.com/products/e6145-utility-box-carrier',
'https://eberbachlabtools.com/products/e6145-large-utility-box-carrier',
'https://eberbachlabtools.com/products/e6145-double-stack-utility-box-carrier',
'https://eberbachlabtools.com/products/e6155-large-box-carrier',
'https://eberbachlabtools.com/products/e6195-controller-mobile-pedestal-mount',
'https://eberbachlabtools.com/products/e6100-platform-for-6-diameter-sieves',
'https://eberbachlabtools.com/products/e6100-platform-for-8-diameter-sieves',
'https://eberbachlabtools.com/products/e6100-platform-for-10-diameter-sieves',
'https://eberbachlabtools.com/products/e6200-18-platform-for-6-diameter-sieves',
'https://eberbachlabtools.com/products/e6200-18-platform-for-8-diameter-sieves',
'https://eberbachlabtools.com/products/e6200-18-platform-for-10-diameter-sieves',
'https://eberbachlabtools.com/products/e6200-18-platform-for-12-diameter-sieves',
'https://eberbachlabtools.com/products/e6200-18-platform-for-18-diameter-sieves',
'https://eberbachlabtools.com/products/el600-12-red-bungee-cord',
'https://eberbachlabtools.com/products/el655-spring-clip',
'https://eberbachlabtools.com/products/e6000-dual-box-carrier-adapter',
'https://eberbachlabtools.com/products/vertical-support-rod',
'https://eberbachlabtools.com/products/e6161-reciprocal-shaker-platform',
'https://eberbachlabtools.com/products/aluminum-pallet-fixture-for-20-liter-cyrovaults',
'https://eberbachlabtools.com/products/shaker-splash-guard',
'https://eberbachlabtools.com/products/flask-carrier',
'https://eberbachlabtools.com/products/flask-carrier-1',
'https://eberbachlabtools.com/products/separatory-funnel-holders',
'https://eberbachlabtools.com/products/19-lengthwise-bar-clamp',
'https://eberbachlabtools.com/products/sieve-shaker',
'https://eberbachlabtools.com/products/variable-speed-sieve-shaker',
'https://eberbachlabtools.com/products/explosion-proof-sieve-shaker',
'https://eberbachlabtools.com/products/double-stack-sieve-shaker',
'https://eberbachlabtools.com/products/variable-speed-double-stack-sieve-shaker',
'https://eberbachlabtools.com/products/explosion-proof-double-stack-sieve-shaker',
'https://eberbachlabtools.com/products/8670-cap-nut-pkg-of-6',
'https://eberbachlabtools.com/products/bearing-cap-8670',
'https://eberbachlabtools.com/products/seal-washer-pkg-of-12-e8670',
'https://eberbachlabtools.com/products/bearing-holder-left-hand-thread-e8670',
'https://eberbachlabtools.com/products/thrust-washer-pkg-of-12-e8670',
'https://eberbachlabtools.com/products/socket-head-drive-shaft-e8670',
'https://eberbachlabtools.com/products/nylon-washer-pkg-of-12-e8670',
'https://eberbachlabtools.com/products/washer-pkg-of-12-e8670',
'https://eberbachlabtools.com/products/hex-nut-left-hand-thread-pkg-of-6',
'https://eberbachlabtools.com/products/standard-size-blades-stainless-steel',
'https://eberbachlabtools.com/products/rubber-gaskets-pkg-of-12',
'https://eberbachlabtools.com/products/semi-micro-blades',
'https://eberbachlabtools.com/products/rubber-gaskets-e8730',
'https://eberbachlabtools.com/products/cap-nut-stainless-steel-e8672',
'https://eberbachlabtools.com/products/bearing-cap-stainless-steel-e8672',
'https://eberbachlabtools.com/products/teflon-seal-washer-pkg-of-12-e8672',
'https://eberbachlabtools.com/products/bearing-holder',
'https://eberbachlabtools.com/products/teflon-gasket-pkg-of-5',
'https://eberbachlabtools.com/products/teflon-gasket-pkg-of-5-e8732',
'https://eberbachlabtools.com/products/3l290r-v-belt-gates-1290',
'https://eberbachlabtools.com/products/8-pulley-x-1-2-bore-7-66-pitch',
'https://eberbachlabtools.com/products/3-75-suction-cup-kit-w-fasteners',
'https://eberbachlabtools.com/products/cable-tie-mount-hole-dia-025-125',
'https://eberbachlabtools.com/products/cable-tie-mount-2-way-internal',
'https://eberbachlabtools.com/products/mdl5-or-gdl5-fuse-5amp-slo-b',
'https://eberbachlabtools.com/products/buss-fuse-holder',
'https://eberbachlabtools.com/products/non-insulated-ring-terminal',
'https://eberbachlabtools.com/products/1-4-quick-disconnect-female-f',
'https://eberbachlabtools.com/products/0-187-quick-disconnect-female-f',
'https://eberbachlabtools.com/products/1-4-female-insulated-quick-connector',
'https://eberbachlabtools.com/products/ac-power-inlet',
'https://eberbachlabtools.com/products/switch-spdt',
'https://eberbachlabtools.com/products/18-ga-machine-tool-wire',
'https://eberbachlabtools.com/products/plug-15a-125v-type-b-115v',
'https://eberbachlabtools.com/products/eberbach-name-plate',
'https://eberbachlabtools.com/products/motor-1-6-hp-1725-1140-rpm',
'https://eberbachlabtools.com/products/6-32-x-1-2-stainless-steel-round-hd-socket-screw',
'https://eberbachlabtools.com/products/10-32-x-3-8-nylon-lock-button-hd-socket-screw',
'https://eberbachlabtools.com/products/8-32-x-1-4-thrust-head-screw',
'https://eberbachlabtools.com/products/1-4-20-x-3-16-set-screw',
'https://eberbachlabtools.com/products/1-4-28-x-3-4-zinc-plated-hex-hd-cap-screw',
'https://eberbachlabtools.com/products/1-4-28-x-1-25-hex-hd-cap-screw',
'https://eberbachlabtools.com/products/no4-x-1-4-pan-head-slotted-sheet-metal-screw',
'https://eberbachlabtools.com/products/6-32-nylon-lock-nut',
'https://eberbachlabtools.com/products/rectangular-steel-speed-nut-1-8',
'https://eberbachlabtools.com/products/8-32-18-8-stainless-steel-machine-screw-nut',
'https://eberbachlabtools.com/products/1-4-28-zinc-plated-grade-5-steel-hex-nut',
'https://eberbachlabtools.com/products/1-4-type-a-wide-zinc-plated-washer',
'https://eberbachlabtools.com/products/1-4-zinc-plated-split-lock-washer',
'https://eberbachlabtools.com/products/black-fiber-washer',
'https://eberbachlabtools.com/products/thrust-washer-515-x-885-x-06-delrin',
'https://eberbachlabtools.com/products/spacer-rod',
'https://eberbachlabtools.com/products/switch-escutcheon-plate',
'https://eberbachlabtools.com/products/shaft-collar',
'https://eberbachlabtools.com/products/rocker-arm-assembly',
'https://eberbachlabtools.com/products/back-panel-assembly',
'https://eberbachlabtools.com/products/ok-12-pulley',
'https://eberbachlabtools.com/products/front-panel-assembly',
'https://eberbachlabtools.com/products/base-assembly',
'https://eberbachlabtools.com/products/crank-sub-assembly',
'https://eberbachlabtools.com/products/top-plate-assembly',
'https://eberbachlabtools.com/products/crank-bearing-bracket-sub-assembly',
'https://eberbachlabtools.com/products/connecting-rod-assembly',
'https://eberbachlabtools.com/products/seamless-brass-tubing',
'https://eberbachlabtools.com/products/3l330r-v-belt',
'https://eberbachlabtools.com/products/fuse-holder',
'https://eberbachlabtools.com/products/5-terminal-grounding-block',
'https://eberbachlabtools.com/products/logo-plate',
'https://eberbachlabtools.com/products/machine-screw',
'https://eberbachlabtools.com/products/hex-head-screw',
'https://eberbachlabtools.com/products/head-screw',
'https://eberbachlabtools.com/products/stainless-steel-nylon-lock-nut',
'https://eberbachlabtools.com/products/socket-cap-screw',
'https://eberbachlabtools.com/products/uss-washer',
'https://eberbachlabtools.com/products/rear-center-panel',
'https://eberbachlabtools.com/products/front-center-panel',
'https://eberbachlabtools.com/products/top-cover',
'https://eberbachlabtools.com/products/motor-pulley',
'https://eberbachlabtools.com/products/speed-adjusting-sticker',
'https://eberbachlabtools.com/products/top-plate-assembly-1',
'https://eberbachlabtools.com/products/crankshaft-assembly',
'https://eberbachlabtools.com/products/right-end-panel-assembly',
'https://eberbachlabtools.com/products/left-end-panel-assembly',
'https://eberbachlabtools.com/products/connecting-rod-assembly-1',
'https://eberbachlabtools.com/products/idler-jackshaft-assembly',
'https://eberbachlabtools.com/products/base-assembly-1',
'https://eberbachlabtools.com/products/wiring-harness-assembly',
'https://eberbachlabtools.com/products/leveling-shim',
'https://eberbachlabtools.com/products/stiffener-spacer',
'https://eberbachlabtools.com/products/bearing-r10-625-bore-x-1-375-o-d',
'https://eberbachlabtools.com/products/retaining-ring',
'https://eberbachlabtools.com/products/suction-cup-foot',
'https://eberbachlabtools.com/products/power-supply',
'https://eberbachlabtools.com/products/power-supply-1',
'https://eberbachlabtools.com/products/keypad-overlay',
'https://eberbachlabtools.com/products/3a-time-delay-fuse',
'https://eberbachlabtools.com/products/crank-body',
'https://eberbachlabtools.com/products/front-panel',
'https://eberbachlabtools.com/products/bronze-bearing',
'https://eberbachlabtools.com/products/bronze-bearing-1',
'https://eberbachlabtools.com/products/bronze-bearing-2',
'https://eberbachlabtools.com/products/motor-1-6-hp-1725-1140-rpm-115v',
'https://eberbachlabtools.com/products/variable-pitch-pulley',
'https://eberbachlabtools.com/products/4l280-v-belt',
'https://eberbachlabtools.com/products/flat-head-phillips-machine-screw',
'https://eberbachlabtools.com/products/flat-head-phillips-machine-screw-1',
'https://eberbachlabtools.com/products/split-lock-washer',
'https://eberbachlabtools.com/products/disc-spring',
'https://eberbachlabtools.com/products/counter-balance',
'https://eberbachlabtools.com/products/1-4-20-x-1-4-sscp',
'https://eberbachlabtools.com/products/30-watt-motor-pkg',
'https://eberbachlabtools.com/products/socket-head-cap-screw',
'https://eberbachlabtools.com/products/mil-spec-washer',
'https://eberbachlabtools.com/products/hex-head-cap-screw',
'https://eberbachlabtools.com/products/hex-head-cap-screw-1',
'https://eberbachlabtools.com/products/5-16-lock-washer',
'https://eberbachlabtools.com/products/stainless-button-head-machine-screw',
'https://eberbachlabtools.com/products/nylon-standoff',
'https://eberbachlabtools.com/products/round-head-machine-screw',
'https://eberbachlabtools.com/products/lock-washer',
'https://eberbachlabtools.com/products/power-supply-bracket',
'https://eberbachlabtools.com/products/6-32-x-1-4-stainless-steel-thpms',
'https://eberbachlabtools.com/products/sae-flat-washer',
'https://eberbachlabtools.com/products/base-assembly-2',
'https://eberbachlabtools.com/products/weight-plate',
'https://eberbachlabtools.com/products/motor-mount',
'https://eberbachlabtools.com/products/hex-head-cap-screw-2',
'https://eberbachlabtools.com/products/elastomer-base',
'https://eberbachlabtools.com/products/elastomer-leg',
'https://eberbachlabtools.com/products/eccentric',
'https://eberbachlabtools.com/products/bearing-collar',
'https://eberbachlabtools.com/products/spring-clip-pad',
'https://eberbachlabtools.com/products/o-ring',
'https://eberbachlabtools.com/products/platform-post',
'https://eberbachlabtools.com/products/top-plate-assembly-2',
'https://eberbachlabtools.com/products/outside-silicone-pad',
'https://eberbachlabtools.com/products/polyethylene-mat',
'https://eberbachlabtools.com/products/top-plate',
'https://eberbachlabtools.com/products/round-head-phillips-machine-screw',
'https://eberbachlabtools.com/products/8-32-x-5-16-stainless-steel-thpms',
'https://eberbachlabtools.com/products/round-head-phillips-machine-screw-1',
'https://eberbachlabtools.com/products/platform-spring-mount',
'https://eberbachlabtools.com/products/4-40-x-1-4-s-s-thpms',
'https://eberbachlabtools.com/products/spring-clip',
'https://eberbachlabtools.com/products/1pc-bottom',
'https://eberbachlabtools.com/products/logo-sticker',
'https://eberbachlabtools.com/products/aluminum-rivet',
'https://eberbachlabtools.com/products/smooth-neoprene-mat',
'https://eberbachlabtools.com/products/1-4-20-x-1-2-thpms-zinc-plated',
'https://eberbachlabtools.com/products/black-rubber-tubing',
'https://eberbachlabtools.com/products/crosswise-bar',
'https://eberbachlabtools.com/products/1-4-oversive-washer',
'https://eberbachlabtools.com/products/knurled-hand-nut',
'https://eberbachlabtools.com/products/base-finished',
'https://eberbachlabtools.com/products/semi-micro-stainless-steel-container-with-threaded-ring',
'https://eberbachlabtools.com/products/rubber-o-ring-seals',
'https://eberbachlabtools.com/products/stainless-steel-screw-top-lid',
'https://eberbachlabtools.com/products/sampling-plug',
'https://eberbachlabtools.com/products/semi-micro-internal-stainless-steel-washer-pkg-of-6',
'https://eberbachlabtools.com/products/stainless-steel-spun-cover',
'https://eberbachlabtools.com/products/semi-micro-stainless-steel-container-w-o-ring',
'https://eberbachlabtools.com/products/screw-cover',
'https://eberbachlabtools.com/products/rubber-o-ring-seals-1',
'https://eberbachlabtools.com/products/1l-stainless-steel-blending-container',
'https://eberbachlabtools.com/products/non-insulated-ring-terminal-1',
'https://eberbachlabtools.com/products/socket-head-screw',
'https://eberbachlabtools.com/products/motor',
'https://eberbachlabtools.com/products/v-belt-electro-analyzer',
'https://eberbachlabtools.com/products/knob-electro-analyzer',
'https://eberbachlabtools.com/products/rubber-foot-electro-analyzer',
'https://eberbachlabtools.com/products/cable-tie-holder',
'https://eberbachlabtools.com/products/support-stand',
'https://eberbachlabtools.com/products/adjustable-stirrer-clamp',
'https://eberbachlabtools.com/products/universal-support-stand-stainless-steel',
'https://eberbachlabtools.com/products/support-stand-rod',
'https://eberbachlabtools.com/products/3383-m05-stationary-knife-blade-set-of-2',
'https://eberbachlabtools.com/products/3383-m10-stainless-steel-stationery-knife-blade-set-of-2',
'https://eberbachlabtools.com/products/vanax-superclean-rotating-blades-for-ed5-mill-set-of-4',
'https://eberbachlabtools.com/products/vanax-superclean-stationary-knife-blade-for-ed5-mill-set-of-4',
'https://eberbachlabtools.com/products/flexible-coupling',
'https://eberbachlabtools.com/products/con-torque-tissue-homogenizer',
'https://eberbachlabtools.com/products/economy-tissue-grinder',
'https://eberbachlabtools.com/products/microplate-vortexer',
'https://eberbachlabtools.com/products/large-microplate-vortexer',
'https://eberbachlabtools.com/products/multi-tube-vortexer',
'https://eberbachlabtools.com/products/waring-single-speed-blender',
'https://eberbachlabtools.com/products/waring-two-speed-blender',
'https://eberbachlabtools.com/products/waring-heavy-duty-2-speed-blender',
'https://eberbachlabtools.com/products/waring-2-speed-blender-with-timer',
'https://eberbachlabtools.com/products/waring-2-speed-heavy-duty-blender-with-timer',
'https://eberbachlabtools.com/products/waring-variable-speed-blender',
'https://eberbachlabtools.com/products/waring-3-speed-4-liter-blender',
'https://eberbachlabtools.com/products/waring-3-speed-4-liter-blender-with-timer',
'https://eberbachlabtools.com/products/waring-variable-speed-4-liter-blender']

for row in myresult:

 try:

    product_url = row

    #page = requests.get(product_url)

    headers = {"User-Agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)", "Referer": "http://example.com"}

    result = requests.get(product_url, headers=headers)

    if result.status_code == 200:

        print("site woking")

    else:

        print("site not working"+result.status_code)

    #a = (result.content.decode())


    soup = BeautifulSoup(result.content,'html.parser')

    #print(soup.prettify())

    title = soup.find("h1",class_="product-meta__title heading h1")
    a = (title.text.strip() if title else "not given")
    print(a)
    sku = soup.find("span",class_="product-meta__sku-number")
    sskkuu=(sku.text.strip() if sku else "not given")
    print(sskkuu)
    price = soup.find("span",class_="price")
    pr = (price.text.strip() if price else "not given")
    print(pr)
    image = soup.find("a",class_="product-gallery__thumbnail is-nav-selected")
    y = (image.get("href") if image else "not given")
    print(y)

    c = (product_url)
    print(c)


    save_details: TextIO = open("eberbach_final.txt", "a+", encoding="utf-8")
    save_details.write("\n"+sskkuu+"\t"+c+"\t"+a+"\t"+pr+"\t"+y)
    save_details.close()
    print("\n**Record stored into txt file.**")






 except AttributeError:

   pass
